// Lidl High-Protein - dinners 1-12.
//
// Yogurt and quark-style dairy do structural work in this book rather than
// sitting on the side: as a marinade that keeps chicken soft through a second
// heating, as the body of a sauce where cream would normally go, and as the
// thing that makes a plain tray of vegetables into a dinner.

import { negligible } from '../../build/plan.mjs';

const ing = (line, display) => ({ line, display: display || line });

export const dinnersA = {
  'skyr-chicken-skewers': {
    name: 'Skyr-Marinated Chicken with Couscous',
    kind: 'dinner',
    tagline: 'Dairy in a marinade does something acid alone cannot: it keeps the chicken soft, tonight and again tomorrow.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('750g chicken thighs', '750g chicken thigh fillets, in large chunks'),
      ing('200g skyr', '200g skyr, for the marinade'),
      ing('450g peppers', '3 peppers, in chunks'),
      ing('2 onion', '2 red onions, in wedges'),
      ing('260g wholemeal couscous dry', '260g couscous'),
      ing('420ml chicken stock'),
      ing('200g low-fat greek yogurt', '200g yogurt, to serve'),
      ing('1 lemon'),
      ing('2 tbsp olive oil'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
      ing(negligible('cumin'), '2 tsp cumin'),
    ],
    method: [
      'Heat the oven to 220&deg;C fan. Mix the skyr with the paprika, cumin, salt and half the lemon juice, and turn the chicken through it until every piece is coated.',
      'Spread the chicken, peppers and onions over a large tray, trickle over the oil, and roast 25 minutes, turning once, until the chicken is cooked through with no pink and the marinade has caught in places.',
      'Pour the hot stock over the couscous, cover with a plate for 8 minutes, then fork it through.',
      'Squeeze the rest of the lemon over the tray and serve on the couscous with the yogurt.',
    ],
    swap: 'Greek yogurt or quark in the marinade. Chicken breast works; cut it larger so it does not dry.',
    leftovers: 'Two lunch portions, good hot or cold. The marinade is why it does not go stringy on reheating.',
  },

  'peppered-steak-bean-mash': {
    name: 'Peppered Steak with White Bean Mash',
    kind: 'dinner',
    tagline: 'Beans mashed with garlic and oil instead of potato: quicker, and it carries a great deal more protein.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('550g lean sirloin steak', '550g sirloin or frying steak'),
      ing('720g cannellini beans', '3 x 400g tins cannellini beans, drained'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('300g green beans'),
      ing('300g broccoli', '300g broccoli, in florets'),
      ing('150g low-fat crème fraîche'),
      ing('300ml beef stock'),
      ing('1 lemon'),
      ing('3 tbsp olive oil'),
      ing(negligible('black pepper'), 'a great deal of black pepper'),
    ],
    method: [
      'Dry the steak on kitchen paper, season it heavily with salt and crushed pepper, and leave it out while you start the beans. Wet steak will not brown.',
      'Warm 2 tbsp of the oil with the garlic in a pan for a minute, add the beans and 100ml of the stock, and crush to a rough mash. Keep it warm.',
      'Boil the broccoli and green beans for 4 minutes and drain.',
      'Get a heavy pan very hot, add the last of the oil, and cook the steak 2&ndash;3 minutes a side for medium. Lift it onto a board to rest for 5 minutes.',
      'Pour the rest of the stock into the pan, scrape up everything stuck to the base, and stir in the cr&egrave;me fra&icirc;che. Slice the steak across the grain and serve with the mash, greens and sauce.',
    ],
    swap: 'Lean beef strips, cooked in two batches. Pork loin works with a minute longer a side.',
    leftovers: 'Two lunch portions. Slice the steak before boxing it, and warm the leftovers gently &mdash; hard reheating is what makes leftover steak grey.',
  },

  'cod-herby-crumb': {
    name: 'Cod with a Herby Crumb',
    kind: 'dinner',
    tagline: 'Breadcrumbs, lemon zest and cheese pressed onto the fish. It takes four minutes to make and turns plain cod into something worth sitting down for.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('680g cod fillet', '680g cod fillets, defrosted'),
      ing('3 slices rye bread', '3 slices bread, blitzed to crumbs'),
      ing('60g parmesan', '60g hard cheese, grated'),
      ing('900g new potatoes', '900g new potatoes, halved'),
      ing('300g green beans'),
      ing('250g frozen peas'),
      ing('1 lemon'),
      ing('3 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Toss the potatoes with 2 tbsp of the oil and plenty of salt and roast 20 minutes.',
      'Mix the breadcrumbs with the cheese, herbs, lemon zest, the last of the oil and a good pinch of salt.',
      'Push the potatoes aside, sit the cod on the tray, and press the crumb firmly onto the top of each fillet.',
      'Roast 12&ndash;14 minutes, until the crumb is golden and the fish is opaque and flakes under a fork.',
      'Boil the green beans and peas for 4 minutes, and serve with the lemon squeezed over.',
    ],
    swap: 'Any white fish, or salmon with two minutes less. Frozen fillets, defrosted in the fridge overnight.',
    leftovers: 'Two lunch portions. The crumb softens overnight, which is a fair trade for not cooking tomorrow.',
  },

  'turkey-ricotta-meatballs': {
    name: 'Turkey and Ricotta Meatballs',
    kind: 'dinner',
    tagline: 'Ricotta does what breadcrumbs do in a beef meatball, and adds protein rather than starch.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('600g turkey mince lean'),
      ing('180g ricotta cheese'),
      ing('1 egg'),
      ing('200g baby spinach'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('1 onion', '1 onion, finely diced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('30g tomato purée'),
      ing('260g wholemeal pasta dry', '260g pasta'),
      ing('60g parmesan', '60g hard cheese, grated'),
      ing('2 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Mix the turkey mince with the ricotta, egg, a third of the garlic, half the herbs, salt and pepper. Stop as soon as it holds together, and roll into about 20 balls.',
      'Brown them in 1 tbsp of the oil in a wide pan, turning, for 6 minutes. They need not be cooked through yet; lift them out.',
      'Cook the onion in the rest of the oil for 6 minutes, then the remaining garlic and herbs for a minute and the tomato pur&eacute;e for another.',
      'Add the tomatoes and a splash of water, return the meatballs, cover and simmer 15 minutes while the pasta boils. Check one is cooked through.',
      'Stir the spinach through at the end to wilt, and finish with the cheese.',
    ],
    swap: 'Cottage cheese blitzed smooth instead of ricotta. Chicken or pork mince instead of turkey.',
    leftovers: 'Two lunch portions, and better on the second day.',
  },

  'salmon-quinoa-bowl': {
    name: 'Salmon and Quinoa Bowl',
    kind: 'dinner',
    tagline: 'Quinoa rather than rice, deliberately: it keeps two days in the fridge without rice&rsquo;s one-day clock.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('600g salmon fillet', '600g salmon fillets'),
      ing('200g quinoa dry', '200g quinoa'),
      ing('300g broccoli', '300g broccoli, in small florets'),
      ing('200g edamame beans'),
      ing('200g cherry tomatoes', '200g cherry tomatoes, halved'),
      ing('200g low-fat greek yogurt'),
      ing('1 lemon'),
      ing('2 tsp mustard'),
      ing('2 tbsp olive oil'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Cook the quinoa in plenty of salted water for 14 minutes, adding the broccoli and edamame for the last 4. Drain well.',
      'Heat the oven to 210&deg;C fan. Season the salmon, sit it on a lined tray, and roast 12&ndash;14 minutes until it flakes and has gone opaque right through.',
      'Whisk the yogurt with the mustard, lemon juice, oil, salt and pepper.',
      'Fold the dressing through the warm quinoa and vegetables, add the tomatoes, and flake the salmon over in large pieces.',
    ],
    swap: 'Any white fish, or two tins of salmon folded through at the end for a much cheaper version.',
    leftovers: 'Two lunch portions, and this is one of the dishes that is genuinely better cold.',
  },

  'spiced-chicken-chickpea-tray': {
    name: 'Spiced Chicken and Chickpea Tray',
    kind: 'dinner',
    tagline: 'One tray, and the chickpeas crisp in the chicken fat while the peppers collapse into a sauce.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('750g chicken thighs', '750g chicken thigh fillets'),
      ing('480g tinned chickpeas', '2 x 400g tins chickpeas, drained and dried'),
      ing('450g peppers', '3 peppers, thickly sliced'),
      ing('2 onion', '2 red onions, in wedges'),
      ing('200g low-fat greek yogurt'),
      ing('3 wholemeal pitta', '3 flatbreads'),
      ing('120g mixed leaves'),
      ing('2 tbsp olive oil'),
      ing('1 lemon'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
      ing(negligible('cumin'), '2 tsp cumin'),
      ing(negligible('chilli powder'), 'chilli powder, to taste'),
    ],
    method: [
      'Heat the oven to 220&deg;C fan. Dry the chickpeas on a tea towel; wet chickpeas steam instead of crisping.',
      'Toss the chicken, chickpeas, peppers and onions with the oil, spices and plenty of salt, and spread over the largest tray in one layer.',
      'Roast 28 minutes, turning once, until the chicken is cooked through and the chickpea skins have started to split.',
      'Squeeze the lemon over the tray and scrape up the juices.',
      'Serve with warm flatbread, the leaves and a heavy spoonful of yogurt.',
    ],
    swap: 'Butter beans instead of chickpeas; they do not crisp but they go creamy, which is a different kind of good.',
    leftovers: 'Two lunch portions. Keep the yogurt and leaves separate until you eat it.',
  },

  'prawn-pea-orzo': {
    name: 'Prawn and Pea Orzo',
    kind: 'dinner',
    tagline: 'Risotto texture without the stirring, and the prawns are in the pan for two minutes at the very end.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('400g king prawns'),
      ing('280g orzo pasta dry', '280g orzo'),
      ing('900ml chicken stock'),
      ing('300g frozen peas'),
      ing('200g baby spinach'),
      ing('1 onion', '1 onion, finely diced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('120g low-fat crème fraîche'),
      ing('60g parmesan', '60g hard cheese, grated'),
      ing('1 lemon'),
      ing('2 tbsp olive oil'),
    ],
    method: [
      'Cook the onion in the oil for 6 minutes, then the garlic for a minute.',
      'Stir in the orzo until it is coated, add the stock, and simmer 12 minutes, stirring now and then so it does not stick.',
      'Add the peas and spinach and cook 3 minutes more.',
      'Add the prawns and cook 2 minutes only, until they are pink and opaque through the middle. Any longer and they tighten.',
      'Off the heat, stir in the cr&egrave;me fra&icirc;che, the cheese and the lemon juice, and season.',
    ],
    swap: 'White fish cut into chunks, added for 4 minutes rather than 2. Frozen prawns, defrosted in the fridge.',
    leftovers: 'Two lunch portions. Reheat only to hot, not to bubbling, or the prawns toughen.',
  },

  'feta-lentil-pepper-bowl': {
    name: 'Feta, Lentil and Roasted Pepper Bowl',
    kind: 'dinner',
    tagline: 'A meat-free dinner that still carries 30g of protein, mostly because of what feta and lentils do together.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('480g lentils cooked', '2 x 400g tins green lentils, drained'),
      ing('450g peppers', '3 peppers, in chunks'),
      ing('400g courgette', '2 courgettes, in half-moons'),
      ing('2 onion', '2 red onions, in wedges'),
      ing('180g reduced-fat feta', '180g feta, crumbled'),
      ing('200g low-fat greek yogurt'),
      ing('40g mixed seeds'),
      ing('2 wholemeal pitta', '2 flatbreads'),
      ing('1 lemon'),
      ing('3 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp dried oregano or mixed herbs'),
    ],
    method: [
      'Heat the oven to 220&deg;C fan. Toss the peppers, courgettes and onions with 3 tbsp of the oil, the herbs and salt, and spread over two trays.',
      'Roast 25 minutes, without stirring for the first 15 so the undersides colour properly.',
      'Warm the lentils through in a pan with the last of the oil and a good pinch of salt.',
      'Fold the roasted vegetables into the lentils with the lemon juice, scraping in everything from the tray.',
      'Crumble the feta over, scatter the seeds, and serve with the yogurt and warm flatbread.',
    ],
    swap: 'Halloumi, browned in a pan, instead of feta. Chickpeas instead of lentils.',
    leftovers: 'Two lunch portions, good cold. Add the feta fresh rather than reheating it.',
  },

  'beef-mushroom-stroganoff': {
    name: 'Beef and Mushroom Stroganoff',
    kind: 'dinner',
    tagline: 'Cr&egrave;me fra&icirc;che rather than cream, stirred in off the heat. Brown the mushrooms properly or the whole thing tastes of nothing.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('550g lean beef strips'),
      ing('500g mushrooms', '500g mushrooms, thickly sliced'),
      ing('2 onion', '2 onions, sliced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('200g low-fat crème fraîche'),
      ing('400ml beef stock'),
      ing('3 tsp mustard'),
      ing('200g quinoa dry', '200g quinoa'),
      ing('250g green beans'),
      ing('2 tbsp olive oil'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Cook the quinoa in salted water for 14 minutes, adding the green beans for the last 4. Drain.',
      'Get a wide pan very hot, add half the oil, and brown the beef in two batches, 90 seconds each, then lift it out. Crowding the pan boils the meat.',
      'Add the rest of the oil and the mushrooms and cook hard for 8 minutes, stirring rarely, until they have given up their water and browned.',
      'Add the onions for 6 minutes, then the garlic and paprika for a minute, then the stock and mustard, and let it reduce by half.',
      'Return the beef, take the pan off the heat, and stir in the cr&egrave;me fra&icirc;che. Season and serve on the quinoa.',
    ],
    swap: 'Pork loin strips, or 400g of mushrooms more and no beef at all.',
    leftovers: 'Two lunch portions. Reheat gently; a hard boil splits the sauce.',
  },

  'tuna-white-bean-pasta': {
    name: 'Tuna and White Bean Pasta',
    kind: 'dinner',
    tagline: 'Two cupboard tins and a lemon. Twenty minutes, and one of the least expensive high-protein dinners in the book.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('300g tinned tuna in spring water', '3 tins tuna, drained'),
      ing('480g cannellini beans', '2 x 400g tins cannellini beans, drained'),
      ing('280g wholemeal pasta dry', '280g pasta'),
      ing('400g tinned tomatoes', '1 x 400g tin chopped tomatoes'),
      ing('6 cloves garlic', '6 cloves garlic, sliced'),
      ing('1 onion', '1 onion, finely diced'),
      ing('200g baby spinach'),
      ing('60g parmesan', '60g hard cheese, grated'),
      ing('1 lemon'),
      ing('3 tbsp olive oil'),
      ing(negligible('chilli flakes'), 'chilli flakes, to taste'),
    ],
    method: [
      'Get the pasta on in well-salted water.',
      'Cook the onion in the oil for 5 minutes, then the garlic and chilli flakes for a minute.',
      'Add the tomatoes and beans, crush about a third of the beans against the side of the pan, and simmer 8 minutes.',
      'Stir in the spinach to wilt, then fold in the tuna and warm it through for a minute only.',
      'Drain the pasta and toss it through with a splash of pasta water, the lemon juice and the cheese.',
    ],
    swap: 'Tinned salmon or mackerel. Chickpeas instead of cannellini.',
    leftovers: 'Two lunch portions, good cold with extra lemon.',
  },

  'pork-apple-slaw': {
    name: 'Pork Loin with Apple Slaw',
    kind: 'dinner',
    tagline: 'A yogurt slaw rather than a sauce, made while the potatoes roast. Sharp enough to cut through the pork.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('650g pork loin', '650g pork loin steaks'),
      ing('900g new potatoes', '900g new potatoes, halved'),
      ing('300g cabbage', '300g white cabbage, finely shredded'),
      ing('2 carrot', '2 carrots, coarsely grated'),
      ing('2 apple', '2 apples, coarsely grated'),
      ing('200g low-fat greek yogurt'),
      ing('3 tsp mustard'),
      ing('1 lemon'),
      ing('250g green beans'),
      ing('3 tbsp olive oil'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Toss the potatoes with 2 tbsp of the oil and salt and roast 30 minutes.',
      'Mix the yogurt, mustard, lemon juice, salt and pepper, then fold through the cabbage, carrot and apple. Leave it to sit; it improves in twenty minutes.',
      'Season the pork well and fry it in the last of the oil over a medium-high heat, 4 minutes a side, until browned and cooked through with no pink. Rest it for five minutes.',
      'Boil the green beans 4 minutes.',
      'Slice the pork and serve with the potatoes, beans and a heap of slaw.',
    ],
    swap: 'Chicken breast, cooked the same way. Pork chops need a couple of minutes longer.',
    leftovers: 'Two lunch portions. The slaw softens overnight but holds; keep it in its own tub.',
  },

  'ham-pea-frittata': {
    name: 'Ham, Pea and Cheese Frittata',
    kind: 'dinner',
    tagline: 'Ten eggs and a handful of ham. Out of the oven with a wobble, and it firms as it rests.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('9 egg', '9 eggs'),
      ing('180g turkey breast slices', '180g sliced ham or turkey, chopped'),
      ing('300g frozen peas'),
      ing('600g new potatoes', '600g new potatoes, sliced'),
      ing('1 onion', '1 onion, sliced'),
      ing('90g cheddar', '90g cheddar, grated'),
      ing('80ml semi-skimmed milk'),
      ing('200g mixed leaves', 'salad, to serve'),
      ing('2 tbsp olive oil'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Heat the oven to 190&deg;C fan. Boil the sliced potatoes for 7 minutes and drain well.',
      'Cook the onion in the oil in a large ovenproof frying pan for 6 minutes, then add the potatoes and ham and warm through.',
      'Beat the eggs with the milk, half the cheese, salt and plenty of pepper, and stir in the peas.',
      'Pour it over, shake the pan to settle everything, and cook on the hob 3 minutes until the edges set.',
      'Scatter the rest of the cheese and bake 14 minutes, until just set with a slight wobble in the middle. Rest 5 minutes before cutting, and serve with salad.',
    ],
    swap: 'Bacon, or leave the meat out and add 200g of browned mushrooms.',
    leftovers: 'Two lunch portions, and frittata is one of the few dishes that is arguably better cold.',
  },
};
