// Lidl High-Protein - dinners 13-24.

import { negligible } from '../../build/plan.mjs';

const ing = (line, display) => ({ line, display: display || line });

export const dinnersB = {
  'chicken-leek-quinoa-broth': {
    name: 'Chicken, Leek and Quinoa Broth',
    kind: 'dinner',
    tagline: 'Somewhere between a soup and a stew, and the only dinner here you could eat from a mug.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('650g chicken thighs', '650g chicken thigh fillets, in chunks'),
      ing('150g quinoa dry', '150g quinoa'),
      ing('300g leek', '2 leeks, sliced'),
      ing('3 carrot', '3 carrots, diced'),
      ing('100g celery', '2 sticks celery, diced'),
      ing('1200ml chicken stock', '1.2 litres chicken stock'),
      ing('240g cannellini beans', '1 x 400g tin cannellini beans, drained'),
      ing('200g baby spinach'),
      ing('1 lemon'),
      ing('2 tbsp olive oil'),
      ing('2 slices rye bread', '2 slices bread, to serve'),
    ],
    method: [
      'Brown the chicken in the oil in a large pan over a high heat, then lift it out.',
      'Cook the leeks, carrots and celery for 8 minutes with a good pinch of salt.',
      'Return the chicken with the quinoa and stock, bring to a simmer and cook 16 minutes, until the quinoa has uncurled and the chicken is cooked through.',
      'Add the beans and spinach for the last 3 minutes.',
      'Season well and finish with lemon juice. Serve with bread.',
    ],
    swap: 'Pearl barley or small pasta instead of quinoa, both a few minutes longer.',
    leftovers: 'Two lunch portions. The quinoa drinks the broth overnight; add a splash of water when reheating.',
  },

  'paneer-pepper-tray': {
    name: 'Paneer and Pepper Tray with Mint Yogurt',
    kind: 'dinner',
    tagline: 'Paneer browns instead of melting, which is the entire reason it works on a tray.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('400g low-fat paneer', '400g paneer, in thick cubes'),
      ing('480g tinned chickpeas', '2 x 400g tins chickpeas, drained and dried'),
      ing('450g peppers', '3 peppers, in chunks'),
      ing('2 onion', '2 red onions, in wedges'),
      ing('240g mint yogurt sauce', '240g mint yogurt or raita'),
      ing('2 wholemeal pitta', '2 flatbreads'),
      ing('200g baby spinach'),
      ing('2 tbsp olive oil'),
      ing('1 lemon'),
      ing(negligible('turmeric'), '1 tsp turmeric'),
      ing(negligible('cumin'), '2 tsp cumin'),
    ],
    method: [
      'Heat the oven to 220&deg;C fan. Toss the chickpeas, peppers and onions with 2 tbsp of the oil, the spices and salt, and roast 18 minutes.',
      'Toss the paneer in the remaining oil, add it to the tray, and roast 12 minutes more until it has taken colour on at least two sides.',
      'Stir the spinach through the hot tray to wilt it.',
      'Squeeze over the lemon and serve with the mint yogurt and warm flatbread.',
    ],
    swap: 'Halloumi, which is saltier &mdash; season the tray less. Firm tofu, pressed first.',
    leftovers: 'Two lunch portions. Paneer softens overnight but keeps its shape.',
  },

  'smoked-haddock-egg': {
    name: 'Smoked Haddock with a Poached Egg',
    kind: 'dinner',
    tagline: 'Poached in milk, which takes the edge off the smoke and gives you the beginnings of a sauce.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('600g smoked haddock fillet', '600g smoked haddock fillets'),
      ing('4 egg', '4 eggs'),
      ing('500ml semi-skimmed milk'),
      ing('900g new potatoes', '900g new potatoes, halved'),
      ing('300g baby spinach'),
      ing('250g frozen peas'),
      ing('120g low-fat crème fraîche'),
      ing('2 tsp mustard'),
      ing('20g butter'),
      ing(negligible('black pepper'), 'plenty of black pepper'),
    ],
    method: [
      'Boil the potatoes in salted water for 16 minutes, adding the peas for the last 4.',
      'Lay the haddock in a wide pan, pour over the milk, and bring to a bare simmer. Poach 8 minutes, until it flakes at a push. Lift the fish out and keep it warm.',
      'Let the poaching milk bubble down by half, then whisk in the cr&egrave;me fra&icirc;che and mustard to make a loose sauce.',
      'Wilt the spinach in the butter in another pan, and poach the eggs for 3 minutes.',
      'Serve the haddock on the spinach and potatoes with an egg on top and the sauce spooned over.',
    ],
    swap: 'Any smoked white fish, or plain cod with a spoon of mustard in the sauce.',
    leftovers: 'Keep two portions of fish and potatoes, and poach fresh eggs tomorrow. A reheated poached egg is not worth eating.',
  },

  'lamb-butterbean-stew': {
    name: 'Lamb and Butter Bean Stew',
    kind: 'dinner',
    tagline: 'Lamb mince browned hard, then beans and tomatoes. Thirty-five minutes for something that tastes like it sat on the hob all afternoon.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('500g lean lamb mince'),
      ing('720g cannellini beans', '3 x 400g tins butter beans, drained'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('2 onion', '2 onions, diced'),
      ing('3 carrot', '3 carrots, diced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('30g tomato purée'),
      ing('300ml beef stock'),
      ing('200g baby spinach'),
      ing('150g low-fat greek yogurt'),
      ing('2 tbsp olive oil'),
      ing(negligible('cumin'), '2 tsp cumin'),
      ing(negligible('cinnamon'), '1 tsp cinnamon'),
    ],
    method: [
      'Brown the lamb mince hard in a dry pan over a high heat, leaving it alone between stirs so it colours. Pour off any excess fat.',
      'Add the oil, onions and carrots and cook 8 minutes, then the garlic, cumin and cinnamon for a minute and the tomato pur&eacute;e for another.',
      'Add the beans, tomatoes and stock and simmer 15 minutes, crushing a few beans against the pan to thicken it.',
      'Stir the spinach through to wilt, and season hard.',
      'Serve with a spoon of yogurt on each plate.',
    ],
    swap: 'Beef mince, which is usually less expensive. Half the lamb and an extra tin of beans works too.',
    leftovers: 'Two lunch portions, and noticeably better the next day.',
  },

  'chicken-caesar-bowl': {
    name: 'Chicken Caesar Bowl',
    kind: 'dinner',
    tagline: 'The dressing thinned with yogurt so it coats rather than clags, and croutons made from the bread that needed using.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('700g chicken breast', '700g chicken breast'),
      ing('4 slices rye bread', '4 slices bread, torn into croutons'),
      ing('300g lettuce', '2 little gem lettuces, chopped'),
      ing('200g low-fat greek yogurt'),
      ing('80g light caesar dressing'),
      ing('80g parmesan', '80g hard cheese, shaved'),
      ing('4 egg', '4 eggs'),
      ing('200g cherry tomatoes', '200g cherry tomatoes, halved'),
      ing('3 tbsp olive oil'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Heat the oven to 200&deg;C fan. Toss the torn bread with 2 tbsp of the oil and salt and bake 10 minutes until crisp.',
      'Boil the eggs for 8 minutes, then cool them under the cold tap and peel.',
      'Season the chicken and fry it in the remaining oil over a medium-high heat for 6&ndash;7 minutes a side, depending on thickness, until cooked through with no pink. Rest, then slice.',
      'Whisk the yogurt into the dressing to loosen it.',
      'Toss the lettuce and tomatoes with the dressing, add the chicken, croutons, halved eggs and shaved cheese.',
    ],
    swap: 'Chicken thighs, which take a couple of minutes longer. Tinned tuna for a no-cook version.',
    leftovers: 'Keep the chicken, eggs and croutons separate from the leaves and dress it in the morning, or lunch is a bowl of wet lettuce.',
  },

  'prawn-tomato-feta-bake': {
    name: 'Prawn, Tomato and Feta Bake',
    kind: 'dinner',
    tagline: 'The prawns go in for the last five minutes only. Everything before that is just a very good tomato sauce.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('450g king prawns'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('180g reduced-fat feta', '180g feta, crumbled'),
      ing('480g cannellini beans', '2 x 400g tins cannellini beans, drained'),
      ing('2 onion', '2 onions, diced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('30g tomato purée'),
      ing('200g baby spinach'),
      ing('4 slices rye bread', '4 thick slices bread, to serve'),
      ing('3 tbsp olive oil'),
      ing('1 lemon'),
      ing(negligible('chilli flakes'), 'chilli flakes, to taste'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Cook the onions in the oil in an ovenproof pan for 8 minutes, then the garlic and chilli flakes for a minute and the tomato pur&eacute;e for another.',
      'Add the tomatoes and beans with a pinch of sugar and salt, and simmer 10 minutes until thickened.',
      'Stir the spinach through to wilt.',
      'Scatter the prawns over the surface, crumble the feta on, and bake 8 minutes until the prawns are pink and opaque and the feta has softened.',
      'Squeeze the lemon over and serve with bread.',
    ],
    swap: 'White fish in chunks, baked for 10 minutes instead of 8.',
    leftovers: 'Two lunch portions. Warm gently; prawns tighten on a hard second heating.',
  },

  'beef-quinoa-chilli': {
    name: 'Beef and Quinoa Chilli',
    kind: 'dinner',
    tagline: 'Quinoa cooked into the chilli instead of served under it, which thickens the sauce and saves a pan.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('500g lean beef mince'),
      ing('150g quinoa dry', '150g quinoa'),
      ing('480g kidney beans', '2 x 400g tins kidney beans, drained'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('2 onion', '2 onions, diced'),
      ing('300g peppers', '2 peppers, diced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('30g tomato purée'),
      ing('600ml beef stock'),
      ing('200g low-fat greek yogurt'),
      ing('60g cheddar', '60g cheddar, grated'),
      ing('2 tbsp olive oil'),
      ing(negligible('cumin'), '2 tsp cumin'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Brown the mince hard in a dry pan over a high heat, leaving it alone between stirs so it colours rather than steams.',
      'Add the oil, onions and peppers and cook 8 minutes, then the garlic and spices for a minute and the tomato pur&eacute;e for another.',
      'Add the quinoa, beans, tomatoes and stock, and simmer 18 minutes, stirring occasionally, until the quinoa has uncurled and the chilli has thickened.',
      'Season hard and serve with the yogurt and cheese on top.',
    ],
    swap: 'Turkey mince, or drop the meat and use a third tin of beans with 300g of browned mushrooms.',
    leftovers: 'Two lunch portions, better on the second day. No rice to worry about, because the quinoa is in it.',
  },

  'miso-tofu-broccoli': {
    name: 'Miso Tofu with Broccoli and Edamame',
    kind: 'dinner',
    tagline: 'Miso and soy give tofu the savoury depth it does not have on its own. Press it while you chop.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('500g firm tofu', '500g firm tofu, pressed and cubed'),
      ing('300g edamame beans'),
      ing('400g broccoli', '400g broccoli, in florets'),
      ing('200g quinoa dry', '200g quinoa'),
      ing('40g miso paste'),
      ing('3 tbsp soy sauce'),
      ing('1 tbsp honey'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('20g ginger', '1 thumb ginger, grated'),
      ing('2 tbsp sesame oil'),
      ing('2 tbsp olive oil'),
      ing('4 spring onion', '4 spring onions, sliced'),
    ],
    method: [
      'Press the tofu between two plates under something heavy while you chop everything else.',
      'Cook the quinoa in salted water for 14 minutes, adding the broccoli and edamame for the last 4. Drain.',
      'Whisk the miso, soy, honey and sesame oil with 4 tbsp of hot water.',
      'Brown the tofu in the olive oil in a very hot pan, leaving each side alone for a minute or two until gold on several faces. Add the garlic and ginger for 30 seconds.',
      'Pour the miso sauce over the tofu, toss for a minute until it glazes, then fold everything through the quinoa and finish with spring onions.',
    ],
    swap: 'Chicken breast or prawns, which need no pressing. Soy and a spoon of peanut butter if there is no miso.',
    leftovers: 'Two lunch portions. Very good cold, which makes it an easy desk lunch.',
  },

  'mackerel-pate-rye': {
    name: 'Smoked Mackerel P&acirc;t&eacute; with Rye and Salad',
    kind: 'dinner',
    tagline: 'A dinner that involves no heat at all beyond a toaster. Fifteen minutes, and the best possible use of a Friday.',
    time: '15 min',
    timeMins: 15,
    yield: 4,
    ingredients: [
      ing('300g smoked mackerel fillet', '300g smoked mackerel, skin off'),
      ing('300g cottage cheese'),
      ing('100g low-fat crème fraîche'),
      ing('6 slices rye bread'),
      ing('300g new potatoes', '300g new potatoes, boiled and cooled'),
      ing('200g cucumber', '200g cucumber, sliced'),
      ing('200g cherry tomatoes', '200g cherry tomatoes, halved'),
      ing('120g mixed leaves'),
      ing('2 lemon', '2 lemons'),
      ing(negligible('black pepper'), 'a great deal of black pepper'),
    ],
    method: [
      'Boil the potatoes for 15 minutes, drain and leave them to cool while you make the p&acirc;t&eacute;.',
      'Flake the mackerel into a bowl, checking carefully for bones.',
      'Mash it with the cottage cheese, cr&egrave;me fra&icirc;che, the juice of one lemon and a lot of pepper. Leave some texture; a smooth p&acirc;t&eacute; is a duller one.',
      'Toast the rye bread.',
      'Serve the p&acirc;t&eacute; with the toast, potatoes and salad, with the second lemon cut into wedges.',
    ],
    swap: 'Tinned mackerel or salmon. Light cream cheese instead of the cottage cheese, for a smoother, richer result.',
    leftovers: 'Two lunch portions. The p&acirc;t&eacute; keeps 48 hours and is arguably better on day two; toast the bread fresh.',
  },

  'halloumi-lentil-tray': {
    name: 'Halloumi and Lentil Tray',
    kind: 'dinner',
    tagline: 'Halloumi roasted rather than fried, so it goes golden without a pan to scrub afterwards.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('350g reduced-fat halloumi', '350g halloumi, in thick slices'),
      ing('480g lentils cooked', '2 x 400g tins green lentils, drained'),
      ing('400g courgette', '2 courgettes, in half-moons'),
      ing('450g peppers', '3 peppers, in chunks'),
      ing('2 onion', '2 red onions, in wedges'),
      ing('200g cherry tomatoes'),
      ing('200g low-fat greek yogurt'),
      ing('40g mixed seeds'),
      ing('1 lemon'),
      ing('2 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Heat the oven to 220&deg;C fan. Toss the courgettes, peppers, onions and tomatoes with 2 tbsp of the oil, the herbs and salt, and spread over two trays.',
      'Roast 20 minutes without stirring, so the undersides colour.',
      'Lay the halloumi slices on top, brush with the remaining oil, and roast 10 minutes more until golden at the edges.',
      'Warm the lentils through in a pan with a pinch of salt, then fold the roasted vegetables into them, scraping in the tray juices.',
      'Scatter the seeds, squeeze over the lemon, and serve with the yogurt.',
    ],
    swap: 'Feta, crumbled on at the end rather than roasted. Chickpeas instead of lentils.',
    leftovers: 'Two lunch portions, good cold. Halloumi firms up in the fridge and softens again in a warm pan.',
  },

  'eggs-bacon-beans': {
    name: 'Baked Eggs with Bacon and Beans',
    kind: 'dinner',
    tagline: 'A pan of smoky beans with eggs cracked into it, which is the Sunday dinner here and cooked at half size.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('8 egg', '8 eggs'),
      ing('150g lean bacon rashers', '150g bacon, chopped'),
      ing('720g cannellini beans', '3 x 400g tins cannellini beans, drained'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('2 onion', '2 onions, sliced'),
      ing('300g peppers', '2 peppers, sliced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('30g tomato purée'),
      ing('70g cheddar', '70g cheddar, grated'),
      ing('2 slices rye bread', '2 thick slices bread'),
      ing('1 tbsp olive oil'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Fry the bacon in the oil in a wide pan for 5 minutes until the fat runs and the edges crisp.',
      'Add the onions and peppers and cook 8 minutes, then the garlic and paprika for a minute and the tomato pur&eacute;e for another.',
      'Add the beans and tomatoes with a pinch of sugar and salt, and simmer 8 minutes until thick enough for a spoon to leave a trail.',
      'Make eight wells and crack an egg into each. Lid on, lowest heat, 6 minutes, until the whites have set and the yolks are still soft.',
      'Scatter the cheese over and serve from the pan with the bread.',
    ],
    swap: 'Leave the bacon out and add an extra tin of beans with a teaspoon of smoked paprika.',
    leftovers: 'None on a Sunday, because it is cooked at half size. If you make the full batch, keep the bean base without eggs and crack fresh ones in tomorrow.',
  },

  'turkey-halloumi-burgers': {
    name: 'Turkey Burgers with Grilled Halloumi',
    kind: 'dinner',
    tagline: 'A slice of halloumi where the cheese slice would go. It does not melt, and that turns out to be better.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('550g turkey mince lean'),
      ing('120g reduced-fat halloumi', '120g halloumi, in 4 slices'),
      ing('1 egg'),
      ing('40g rolled oats', '40g porridge oats'),
      ing('1 onion', '1 onion, coarsely grated'),
      ing('650g potato', '650g potatoes, in wedges'),
      ing('4 wholemeal roll', '4 rolls'),
      ing('150g low-fat greek yogurt'),
      ing('100g mixed leaves'),
      ing('150g tomatoes', '1 large tomato, sliced'),
      ing('3 tbsp olive oil'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Toss the wedges with 2 tbsp of the oil, the paprika and salt and roast 30 minutes, turning once.',
      'Squeeze the grated onion out over the sink, then mix it with the turkey mince, egg, oats, salt and pepper.',
      'Shape four patties wider than the rolls and press a dent into the middle of each so they stay flat.',
      'Fry in the rest of the oil over a medium-high heat, 5&ndash;6 minutes a side, until cooked through with no pink. Lift them out and grill the halloumi in the same pan for a minute a side.',
      'Build in the rolls with the yogurt, leaves, tomato and a slice of halloumi on each.',
    ],
    swap: 'Chicken mince, or beef if you want the fat back. A slice of cheddar instead of halloumi.',
    leftovers: 'Two patties and the spare wedges. Reheat in the oven rather than the microwave.',
  },
};
