// Aldi Budget - dinners 1-12.
//
// Every dinner yields four portions: two eaten tonight, two refrigerated for
// tomorrow's lunch. Sunday's dinner is the same recipe cooked at half scale.
//
// `timeMins` is total elapsed time from a cold kitchen, including chopping and
// oven preheating, and the build refuses anything over 40.
//
// Where a dish is served on rice, the rice is cooked fresh both nights rather
// than refrigerated: FSA guidance keeps cooked rice to one day and one reheat,
// and a batch of rice sitting in a tub is the one avoidable risk in the plan.

import { negligible } from '../../build/plan.mjs';

const ing = (line, display) => ({ line, display: display || line });

export const dinnersA = {
  chilli: {
    name: 'Beef and Bean Chilli',
    kind: 'dinner',
    tagline: 'Half mince, half beans. The beans take on the flavour of the meat and nobody at the table counts the difference.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('450g lean beef mince', '450g lean beef mince (5%)'),
      ing('2 onion', '2 onions, diced'),
      ing('300g peppers', '2 peppers, diced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('480g kidney beans', '2 x 400g tins kidney beans, drained'),
      ing('30g tomato purée'),
      ing('2 tbsp olive oil'),
      ing('250g brown rice dry', '250g brown rice, cooked fresh'),
      ing(negligible('cumin'), '2 tsp ground cumin'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
      ing(negligible('chilli powder'), 'chilli powder, to taste'),
    ],
    method: [
      'Brown the beef mince in a dry pan over a high heat, leaving it alone a minute at a time so it colours rather than steams. Grey mince tastes boiled.',
      'Turn the heat down, add the oil, onions and peppers, and cook 6 minutes.',
      'Garlic, cumin, paprika and chilli for a minute, then the tomato purée for one more so it darkens.',
      'Add the tomatoes and kidney beans with a splash of water. Simmer 15 minutes, until a spoon drawn through leaves a mark for a second.',
      'Meanwhile boil the rice for 25 minutes. Season the chilli hard and serve. Two portions go into tubs, cooled quickly.',
    ],
    swap: 'A third tin of beans in place of the mince takes a good chunk off the cost and most people do not notice.',
    leftovers: 'Two lunch portions, better on day two. Cook rice fresh again tomorrow rather than keeping tonight’s.',
  },

  dhal: {
    name: 'Red Lentil Dhal with Warm Pitta',
    kind: 'dinner',
    tagline: 'Lentils, a tin of tomatoes and one pan. The spiced oil poured over at the end is what turns it from worthy into something you look forward to.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('320g red lentils dry', '320g red lentils, rinsed'),
      ing('400g tinned tomatoes', '1 x 400g tin chopped tomatoes'),
      ing('2 onion', '2 onions, diced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('20g ginger', '1 thumb ginger, grated'),
      ing('900ml vegetable stock'),
      ing('4 tbsp olive oil'),
      ing('4 wholemeal pitta', '4 wholemeal pittas'),
      ing('150g low-fat natural yogurt', '150g natural yogurt, to serve'),
      ing(negligible('turmeric'), '2 tsp turmeric'),
      ing(negligible('cumin'), '2 tsp ground cumin, plus 1 tsp seeds'),
    ],
    method: [
      'Cook the onions in 2 tbsp of the oil for 6 minutes, then add the garlic, ginger, turmeric and ground cumin for a minute.',
      'Add the lentils, tomatoes and stock. Bring to the boil, then simmer 20 minutes, stirring every few minutes so nothing catches on the base.',
      'It is ready when the lentils have collapsed completely. Season harder than feels right; lentils absorb salt.',
      'Heat the remaining 2 tbsp oil in a small pan until it shimmers, add the cumin seeds and swirl for 30 seconds until they smell nutty. Watch it &mdash; it burns in seconds.',
      'Pour the spiced oil over the dhal, stir once, and serve with warm pitta and a spoon of yogurt.',
    ],
    swap: 'A handful of spinach stirred in at the end costs little and adds iron.',
    leftovers: 'Two lunch portions. It thickens overnight; loosen with a splash of boiling water when you reheat it.',
  },

  'lemon-chicken-couscous': {
    name: 'Lemon Chicken and Couscous Traybake',
    kind: 'dinner',
    tagline: 'Couscous instead of rice on purpose: it keeps two days in the fridge without rice’s one-day clock.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('640g chicken thighs', '640g chicken thigh fillets, in large pieces'),
      ing('300g peppers', '2 peppers, in chunks'),
      ing('1 onion', '1 red onion, in wedges'),
      ing('240g tinned chickpeas', '1 x 400g tin chickpeas, drained'),
      ing('280g wholemeal couscous dry', '280g couscous'),
      ing('450ml chicken stock'),
      ing('3 tbsp olive oil'),
      ing('1 lemon'),
      ing('100g low-fat natural yogurt', '100g natural yogurt, to serve'),
      ing(negligible('cumin'), '2 tsp ground cumin'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Heat the oven to 200&deg;C fan. Toss the chicken thighs, peppers, onion and chickpeas on a large tray with the oil, cumin, paprika, salt and pepper.',
      'Roast 25 minutes, turning once halfway, until the chicken is cooked through and the edges have caught.',
      'While it roasts, pour the hot stock over the couscous, cover with a plate and leave 8 minutes, then fork it through.',
      'Squeeze the lemon over the tray and scrape up the juices; they are the best part of it.',
      'Serve over the couscous with a spoon of yogurt. Two portions into tubs once they stop steaming.',
    ],
    swap: 'Chicken breast works but dries out on reheating. Thighs are more forgiving and usually cheaper.',
    leftovers: 'Two lunch portions, good hot or cold, within 48 hours.',
  },

  'bacon-mushroom-pasta': {
    name: 'Bacon, Mushroom and Pea Pasta',
    kind: 'dinner',
    tagline: 'Yogurt instead of cream, stirred in off the heat so it cannot split. Twenty minutes, one pan and a pot.',
    time: '20 min',
    timeMins: 20,
    yield: 4,
    ingredients: [
      ing('200g back bacon rashers', '200g bacon, chopped'),
      ing('400g mushrooms', '400g mushrooms, sliced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('360g wholemeal pasta dry', '360g pasta'),
      ing('200g frozen peas'),
      ing('200g low-fat greek yogurt'),
      ing('60g parmesan', '60g hard cheese, grated'),
      ing('1 tbsp olive oil'),
      ing(negligible('black pepper'), 'plenty of black pepper'),
    ],
    method: [
      'Get the pasta on in well-salted water and add the peas for the last two minutes.',
      'Fry the bacon in the oil until the fat runs and the edges crisp, about 5 minutes, then lift it out and leave the fat behind.',
      'Add the mushrooms to that fat and cook hard for 6 minutes without stirring much, until they have given up their water and browned. This is where the flavour is.',
      'Garlic for a minute. Save a mug of pasta water, then drain and add the pasta, peas and bacon to the pan.',
      'Off the heat, stir in the yogurt, cheese and a splash of pasta water until it coats. Black pepper, and serve.',
    ],
    swap: 'Leave the bacon out, double the mushrooms and add a teaspoon of soy sauce for the savoury note it loses.',
    leftovers: 'Two lunch portions. Reheat gently &mdash; a yogurt sauce dislikes a rolling boil.',
  },

  'cod-potato-pea-traybake': {
    name: 'Cod, Potato and Pea Traybake',
    kind: 'dinner',
    tagline: 'Frozen fish is one of the few things in a discounter that is both cheap and genuinely good. Defrost it overnight and this is a half-hour dinner.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('600g cod fillet', '600g cod fillets, defrosted'),
      ing('1kg new potatoes', '1kg new potatoes, halved'),
      ing('300g frozen peas'),
      ing('300g leek', '2 leeks, sliced'),
      ing('4 tbsp olive oil'),
      ing('1 lemon'),
      ing('60g parmesan', '60g hard cheese, grated'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Toss the potatoes with 3 tbsp of the oil, the herbs and plenty of salt on a large tray and roast 20 minutes.',
      'Add the leeks, toss them through the potatoes, and roast another 5 minutes.',
      'Make space for the cod fillets, brush them with the last of the oil, season, and scatter the frozen peas around them.',
      'Roast a final 10 minutes, until the cod is opaque all the way through and flakes when you push it with a fork.',
      'Lemon squeezed over, cheese scattered on, and serve straight from the tray.',
    ],
    swap: 'Any white fish, or salmon if it is on offer. Frozen fillets are fine &mdash; defrost them in the fridge overnight, not on the worktop.',
    leftovers: 'Two lunch portions. Cooked fish keeps 48 hours and is good cold with the potatoes.',
  },

  meatballs: {
    name: 'Beef Meatballs in Tomato Sauce',
    kind: 'dinner',
    tagline: 'Bread soaked in milk is what keeps a cheap meatball tender. Skip it and you get small grey bouncing things.',
    time: '40 min',
    timeMins: 40,
    yield: 4,
    ingredients: [
      ing('500g lean beef mince'),
      ing('2 slices wholemeal bread', '2 slices bread, crusts off, torn'),
      ing('60ml semi-skimmed milk'),
      ing('1 egg'),
      ing('1 onion', '1 onion, finely diced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('30g tomato purée'),
      ing('300g wholemeal pasta dry', '300g pasta'),
      ing('40g parmesan', '40g hard cheese, grated'),
      ing('2 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Soak the torn bread in the milk for five minutes, then squeeze it out and mash it to a paste.',
      'Mix that paste with the beef mince, egg, one crushed garlic clove, half the herbs, salt and pepper. Use your hands and stop the moment it comes together; overworking makes them springy. Roll into about 20 balls.',
      'Brown the meatballs in 1 tbsp of the oil in a wide pan, turning them, for 6 minutes. They do not need to be cooked through yet. Lift them out.',
      'Cook the onion in the rest of the oil for 6 minutes, add the remaining garlic and herbs for a minute, then the tomato purée for another, then the tinned tomatoes and a splash of water.',
      'Return the meatballs, cover, and simmer 15 minutes while the pasta boils. Check one is cooked through, then finish with the cheese.',
    ],
    swap: 'Turkey mince makes a leaner ball and needs the bread trick even more than beef does.',
    leftovers: 'Two lunch portions. Best of all in a roll with the sauce spooned over.',
  },

  'spanish-eggs': {
    name: 'Spanish-Style Eggs with Peppers and Beans',
    kind: 'dinner',
    tagline: 'Eggs poached straight into a smoky pepper stew. One pan, and bread to get the last of it off the plate.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('8 egg', '8 eggs'),
      ing('450g peppers', '3 peppers, sliced'),
      ing('2 onion', '2 onions, sliced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('480g cannellini beans', '2 x 400g tins cannellini beans, drained'),
      ing('30g tomato purée'),
      ing('3 tbsp olive oil'),
      ing('4 slices wholemeal bread', '4 thick slices bread'),
      ing('60g cheddar', '60g cheddar, grated'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Cook the onions and peppers in the oil in a wide pan for 10 minutes, until soft and beginning to colour at the edges.',
      'Garlic and paprika for a minute, then the tomato purée for one more.',
      'Add the tomatoes and beans with a pinch of sugar and salt, and simmer 8 minutes until thick enough that a spoon leaves a trail.',
      'Make eight wells with the back of a spoon and crack an egg into each. Lid on, lowest heat, 5&ndash;6 minutes, until the whites have set and the yolks are still soft.',
      'Scatter the cheese over, and serve from the pan with the bread.',
    ],
    swap: 'A chopped pepper-and-onion mix from the freezer saves ten minutes of knife work.',
    leftovers: 'Keep two portions of the stew without eggs, and poach fresh eggs into it tomorrow &mdash; a reheated poached egg is a sad thing.',
  },

  'turkey-ragu-pasta': {
    name: 'Turkey and Vegetable Ragù',
    kind: 'dinner',
    tagline: 'Turkey mince is lean enough to need help, so the vegetables are grated in and the milk step does the rest.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('500g turkey mince lean'),
      ing('2 carrot', '2 carrots, coarsely grated'),
      ing('2 onion', '2 onions, finely diced'),
      ing('200g mushrooms', '200g mushrooms, finely chopped'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('30g tomato purée'),
      ing('150ml semi-skimmed milk'),
      ing('300g wholemeal pasta dry', '300g pasta'),
      ing('60g parmesan', '60g hard cheese, grated'),
      ing('2 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Brown the turkey mince hard in 1 tbsp of the oil, breaking it up. Lean mince catches easily, so keep it moving once it colours.',
      'Add the rest of the oil with the onion, grated carrot and mushrooms and cook 8 minutes until everything has softened and shrunk.',
      'Garlic and herbs for a minute, then the tomato purée for another.',
      'Pour in the milk and let it bubble away almost completely, about 5 minutes. It sounds odd and it is what makes a lean ragù taste rich.',
      'Add the tomatoes, simmer 12 minutes while the pasta boils, season well, and finish with the cheese.',
    ],
    swap: 'Beef mince if turkey is not on the shelf. A tin of green lentils replaces half the mince and stretches it further.',
    leftovers: 'Two lunch portions, and it is better tomorrow than it is tonight.',
  },

  'chickpea-curry': {
    name: 'Tomato and Chickpea Curry',
    kind: 'dinner',
    tagline: 'Two tins, a bag of frozen spinach and twenty-five minutes. The onions are the only part you cannot rush.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('480g tinned chickpeas', '2 x 400g tins chickpeas, drained'),
      ing('400g tinned tomatoes', '1 x 400g tin chopped tomatoes'),
      ing('200ml coconut milk light'),
      ing('2 onion', '2 onions, sliced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('20g ginger', '1 thumb ginger, grated'),
      ing('200g spinach', '200g frozen spinach'),
      ing('30g tomato purée'),
      ing('2 tbsp olive oil'),
      ing('300g brown rice dry', '300g brown rice, cooked fresh'),
      ing('16g curry powder', '2 tbsp curry powder'),
    ],
    method: [
      'Cook the onions in the oil over a medium heat for 8 minutes, until properly soft and gold at the edges. Undercooked onion is why most home curries taste thin.',
      'Garlic, ginger and curry powder for a minute, then the tomato purée for another.',
      'Add the chickpeas, tomatoes and coconut milk and simmer 12 minutes while the rice boils.',
      'Stir the frozen spinach through for the last 3 minutes.',
      'Season, and add a squeeze of lemon if you have one. A flat curry almost always wants acid rather than more curry powder.',
    ],
    swap: 'Butter beans in place of one chickpea tin give a creamier result.',
    leftovers: 'Two lunch portions of the curry. Boil rice fresh tomorrow rather than storing tonight’s.',
  },

  'chicken-fajita-bowls': {
    name: 'Chicken Fajita Bowls',
    kind: 'dinner',
    tagline: 'Everything on one tray, wrapped at the table. The lime and yogurt at the end stop it being just hot chicken.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('520g chicken thighs', '520g chicken thigh fillets, sliced'),
      ing('450g peppers', '3 peppers, sliced'),
      ing('2 onion', '2 red onions, sliced'),
      ing('320g black beans', '1 x 400g tin black beans, drained'),
      ing('4 wholemeal tortilla', '4 large tortilla wraps'),
      ing('150g low-fat natural yogurt'),
      ing('60g cheddar', '60g cheddar, grated'),
      ing('1 lemon', '1 lime or lemon'),
      ing('2 tbsp olive oil'),
      ing('20g fajita spice', '2 tbsp fajita seasoning'),
    ],
    method: [
      'Heat the oven to 220&deg;C fan. Toss the sliced chicken, peppers and onions with the oil and fajita seasoning on the largest tray you own.',
      'Spread it into one layer &mdash; crowded, it steams instead of roasting &mdash; and roast 20 minutes, turning once.',
      'Warm the black beans in a small pan with a splash of water and a pinch of salt.',
      'Check the chicken is cooked through with no pink, then squeeze the lime over the tray.',
      'Warm the tortillas, and build at the table with the beans, yogurt and cheese.',
    ],
    swap: 'Make your own seasoning from paprika, cumin, garlic powder and a pinch of chilli if the sachets are out of stock.',
    leftovers: 'Two lunch portions of the tray and beans. Keep the wraps and yogurt separate until the morning.',
  },

  'tuna-tomato-spaghetti': {
    name: 'Tuna, Tomato and Olive Spaghetti',
    kind: 'dinner',
    tagline: 'A cupboard dinner that does not taste like one. Twenty minutes, and the only fresh thing in it is garlic.',
    time: '20 min',
    timeMins: 20,
    yield: 4,
    ingredients: [
      ing('300g tinned tuna in spring water', '3 tins tuna, drained'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('120g olives', '120g olives, halved'),
      ing('4 cloves garlic', '4 cloves garlic, sliced'),
      ing('1 onion', '1 onion, finely diced'),
      ing('30g tomato purée'),
      ing('360g wholemeal pasta dry', '360g spaghetti'),
      ing('3 tbsp olive oil'),
      ing('1 lemon'),
      ing(negligible('chilli flakes'), 'chilli flakes, to taste'),
    ],
    method: [
      'Get the spaghetti on in well-salted water.',
      'Cook the onion in the oil for 5 minutes, then the garlic and chilli flakes for one, then the tomato purée for one more.',
      'Add the tomatoes and olives and simmer hard for 8 minutes so it thickens rather than waters the pasta down.',
      'Fold the drained tuna through at the end and warm it for a minute only. Boiling tuna makes it woolly.',
      'Drain the spaghetti, toss it through the sauce with a splash of pasta water, and finish with lemon.',
    ],
    swap: 'Tinned mackerel gives a richer, oilier sauce for about the same money.',
    leftovers: 'Two lunch portions, good cold as a pasta salad with a little extra lemon.',
  },

  'mince-and-mash': {
    name: 'Mince and Mash with Onion Gravy',
    kind: 'dinner',
    tagline: 'Cottage pie without the oven stage, which is what gets it under the half hour. The Worcestershire-style kick comes from mustard and stock.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('500g lean beef mince'),
      ing('2 onion', '2 onions, sliced'),
      ing('3 carrot', '3 carrots, diced small'),
      ing('480g lentils cooked', '2 x 400g tins green lentils, drained'),
      ing('600ml beef stock'),
      ing('2 tsp mustard'),
      ing('900g potato', '900g potatoes, peeled and quartered'),
      ing('80ml semi-skimmed milk'),
      ing('20g butter'),
      ing('300g frozen peas'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Get the potatoes into salted water and boil 18 minutes until a knife slides through.',
      'Brown the beef mince hard in a dry pan, then add the onions and carrots and cook 8 minutes.',
      'Stir in the herbs and mustard, then the lentils and stock, and simmer 12 minutes until it thickens into a gravy rather than a soup.',
      'Boil the peas for 3 minutes at the end.',
      'Drain the potatoes, let them steam dry in the pan for two minutes, then mash with the milk and butter and season properly. Mash is mostly salt.',
    ],
    swap: 'All lentils and 200g of mushrooms browned hard makes a meat-free version at a fraction of the cost.',
    leftovers: 'Two lunch portions. It reheats better than almost anything else in the book.',
  },
};
