// Aldi Budget - dinners 13-24.

import { negligible } from '../../build/plan.mjs';

const ing = (line, display) => ({ line, display: display || line });

export const dinnersB = {
  'chicken-chickpea-curry': {
    name: 'Chicken, Chickpea and Spinach Curry',
    kind: 'dinner',
    tagline: 'Thighs rather than breast, because they hold up to a second heating without turning to string.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('600g chicken thighs', '600g chicken thigh fillets, in chunks'),
      ing('240g tinned chickpeas', '1 x 400g tin chickpeas, drained'),
      ing('400g tinned tomatoes', '1 x 400g tin chopped tomatoes'),
      ing('200ml coconut milk light'),
      ing('2 onion', '2 onions, sliced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('20g ginger', '1 thumb ginger, grated'),
      ing('200g spinach', '200g frozen spinach'),
      ing('30g tomato purée'),
      ing('2 tbsp olive oil'),
      ing('250g brown rice dry', '250g brown rice, cooked fresh'),
      ing('16g curry powder', '2 tbsp curry powder'),
    ],
    method: [
      'Brown the chicken in the oil over a high heat until coloured on all sides, then lift it out.',
      'Cook the onions in the same pan for 8 minutes until soft and gold.',
      'Garlic, ginger and curry powder for a minute, then the tomato purée for another.',
      'Return the chicken with the chickpeas, tomatoes and coconut milk. Simmer 15 minutes while the rice boils, until the chicken is cooked through and the sauce has thickened.',
      'Stir in the frozen spinach for the last 3 minutes and season.',
    ],
    swap: 'Drop the chicken and use a second tin of chickpeas plus 200g mushrooms for a meat-free version.',
    leftovers: 'Two lunch portions of the curry. Cook rice fresh tomorrow rather than keeping tonight’s.',
  },

  'tuna-pasta-bake': {
    name: 'Tuna and Sweetcorn Pasta Bake',
    kind: 'dinner',
    tagline: 'A white sauce from scratch takes four minutes and about thirty pence. The jar version is neither.',
    time: '40 min',
    timeMins: 40,
    yield: 4,
    ingredients: [
      ing('300g wholemeal pasta dry', '300g pasta'),
      ing('300g tinned tuna in spring water', '3 tins tuna, drained'),
      ing('200g sweetcorn', '200g tinned sweetcorn, drained'),
      ing('30g butter'),
      ing('40g wholemeal flour'),
      ing('550ml semi-skimmed milk'),
      ing('90g cheddar', '90g cheddar, grated'),
      ing('2 tsp mustard'),
      ing('200g frozen peas'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Heat the oven to 200&deg;C fan. Boil the pasta three minutes short of the packet time, adding the peas for the last two, then drain.',
      'Melt the butter in a pan, stir in the flour and cook it for a minute so it loses the raw taste.',
      'Add the milk a splash at a time, stirring hard after each, until you have a smooth sauce. Simmer 3 minutes until it coats the back of a spoon.',
      'Off the heat, stir in the mustard, two thirds of the cheese, salt and plenty of pepper.',
      'Fold through the pasta, peas, tuna and sweetcorn, tip into a dish, scatter the rest of the cheese and bake 18 minutes until browned at the edges.',
    ],
    swap: 'Tinned salmon, or a tin of butter beans for a version with no fish in it at all.',
    leftovers: 'Two lunch portions. Reheat covered so the top does not turn to leather.',
  },

  'egg-fried-rice': {
    name: 'Egg Fried Rice with Peas and Bacon',
    kind: 'dinner',
    tagline: 'The Sunday dinner, cooked at half size because there is no lunch to feed on Monday. All about how hot the pan gets.',
    time: '20 min',
    timeMins: 20,
    yield: 4,
    ingredients: [
      ing('270g brown rice dry', '270g brown rice, cooked and cooled'),
      ing('8 egg', '8 eggs, beaten'),
      ing('150g back bacon rashers', '150g bacon, diced'),
      ing('300g frozen peas'),
      ing('6 spring onion', '6 spring onions, sliced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('4 tbsp soy sauce'),
      ing('2 tbsp sesame oil'),
      ing('1 tbsp olive oil'),
    ],
    method: [
      'Boil the rice, drain it, and spread it on a tray to cool quickly while you prepare everything else. Cold, dry rice fries; warm rice steams into paste.',
      'Get a large pan very hot. Add the olive oil and the beaten egg, scramble it hard for 30 seconds, and tip it onto a plate.',
      'Fry the bacon in the same pan for 4 minutes until it crisps, then add the garlic and the white parts of the spring onion for 20 seconds.',
      'Add the rice and press it flat, leaving it 30 seconds at a time between stirs so it catches and crisps. Add the peas and toss for 2 minutes.',
      'Return the egg, add the soy sauce around the edge of the pan rather than into the middle, and finish with the sesame oil and the green spring onion.',
    ],
    swap: 'Leave the bacon out and use ten eggs; it is still a substantial plate.',
    leftovers: 'None, by design. This is cooked at half size on a Sunday and eaten the same night &mdash; cooked rice is reheated once only, and frying it was that once.',
  },

  'turkey-sausage-bean-pan': {
    name: 'Turkey Sausage and Butter Bean Pan',
    kind: 'dinner',
    tagline: 'Sausages, beans and a tray of potatoes cooked together until the sausage fat has got into everything.',
    time: '40 min',
    timeMins: 40,
    yield: 4,
    ingredients: [
      ing('500g turkey sausages', '10 turkey sausages'),
      ing('800g potato', '800g potatoes, in 3cm chunks'),
      ing('2 onion', '2 onions, in wedges'),
      ing('480g cannellini beans', '2 x 400g tins cannellini beans, drained'),
      ing('400g tinned tomatoes', '1 x 400g tin chopped tomatoes'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('200g cabbage', '200g cabbage or kale, shredded'),
      ing('3 tbsp olive oil'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Heat the oven to 200&deg;C fan. Toss the potatoes and onions with the oil, paprika and salt in a deep tray and roast 18 minutes.',
      'Nestle the sausages among the potatoes and roast another 12 minutes, until they are browned and cooked through.',
      'Stir in the beans, tomatoes and garlic with a splash of water, scraping the base of the tray as you go.',
      'Back in for 8 minutes, adding the shredded cabbage for the last 4 so it wilts but keeps some bite.',
      'Season and serve straight from the tray.',
    ],
    swap: 'Any sausage. Vegetarian sausages need no other change to the method.',
    leftovers: 'Two lunch portions, and good cold as well as hot.',
  },

  'lentil-bolognese': {
    name: 'Mushroom and Lentil Bolognese',
    kind: 'dinner',
    tagline: 'Brown the mushrooms properly and nobody asks where the meat went. The milk step looks wrong and is the best part of it.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('480g lentils cooked', '2 x 400g tins green lentils, drained'),
      ing('400g mushrooms', '400g mushrooms, finely chopped'),
      ing('2 onion', '2 onions, finely diced'),
      ing('2 carrot', '2 carrots, finely diced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('30g tomato purée'),
      ing('150ml semi-skimmed milk'),
      ing('300g wholemeal pasta dry', '300g spaghetti'),
      ing('60g parmesan', '60g hard cheese, grated'),
      ing('2 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Brown the mushrooms hard in 2 tbsp of the oil for 8 minutes, stirring rarely, until they have released their water and taken on colour.',
      'Add the rest of the oil with the onion and carrot and cook 8 minutes, then the garlic and herbs for a minute and the tomato purée for another.',
      'Pour in the milk and simmer until it has almost disappeared, about 4 minutes.',
      'Add the tomatoes and lentils with a splash of water and simmer 12 minutes while the pasta boils.',
      'Season hard &mdash; a meat-free sauce needs noticeably more salt &mdash; and finish with the cheese.',
    ],
    swap: 'Half lentils, half beef mince if you want it meatier without the full cost.',
    leftovers: 'Two lunch portions, better the next day.',
  },

  'chicken-noodle-stirfry': {
    name: 'Chicken and Cabbage Noodle Stir-Fry',
    kind: 'dinner',
    tagline: 'Chop everything before the hob goes on. Once it starts there is no time to catch up.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('600g chicken thighs', '600g chicken thigh fillets, sliced thin'),
      ing('300g wholewheat noodles dry', '300g egg noodles'),
      ing('300g cabbage', '300g cabbage, shredded'),
      ing('2 carrot', '2 carrots, cut into matchsticks'),
      ing('300g peppers', '2 peppers, sliced'),
      ing('4 cloves garlic', '4 cloves garlic, sliced'),
      ing('20g ginger', '1 thumb ginger, grated'),
      ing('4 tbsp soy sauce'),
      ing('2 tbsp honey'),
      ing('1 tbsp vinegar'),
      ing('3 tbsp olive oil'),
    ],
    method: [
      'Mix the soy, honey and vinegar in a cup. Chop everything else. Only then turn the hob on.',
      'Boil the noodles, drain, and toss with a few drops of oil so they do not weld together.',
      'Get a large pan very hot. Add 1 tbsp oil and half the chicken in a single layer, leave it 90 seconds without touching it, then stir until cooked through, about 3 minutes. Repeat with the second half and set both aside.',
      'Add the rest of the oil with the cabbage, carrots and peppers and stir-fry 4 minutes, then the garlic and ginger for 30 seconds.',
      'Return the chicken and noodles, pour the sauce round the edge of the pan, and toss hard for a minute until everything is glossy.',
    ],
    swap: 'Two eggs scrambled in at the end instead of the chicken, or a block of firm tofu browned first.',
    leftovers: 'Two lunch portions. The noodles soften overnight but the flavour holds.',
  },

  frittata: {
    name: 'Potato, Pepper and Cheese Frittata',
    kind: 'dinner',
    tagline: 'The dinner that exists to clear the vegetable drawer. Take it out with a wobble and it firms as it rests.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('10 egg', '10 eggs'),
      ing('600g potato', '600g potatoes, thinly sliced'),
      ing('300g peppers', '2 peppers, sliced'),
      ing('2 onion', '2 onions, sliced'),
      ing('90g cheddar', '90g cheddar, grated'),
      ing('80ml semi-skimmed milk'),
      ing('3 tbsp olive oil'),
      ing('120g mixed leaves', 'salad, to serve'),
      ing('4 slices wholemeal bread', '4 slices bread, to serve'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Heat the oven to 190&deg;C fan. Boil the sliced potatoes for 6 minutes, then drain them well.',
      'Cook the onions and peppers in the oil in a large ovenproof frying pan for 8 minutes, then add the potatoes and warm them through.',
      'Beat the eggs with the milk, half the cheese, salt and plenty of pepper.',
      'Pour the eggs over, shake the pan to settle everything, and cook on the hob 3 minutes until the edges set.',
      'Scatter the rest of the cheese and bake 14 minutes, until just set with a slight wobble in the middle. Rest 5 minutes before cutting, and serve with salad and bread.',
    ],
    swap: 'Any cooked vegetable. Avoid raw courgette unless you cook it off first, or it waters the eggs down.',
    leftovers: 'Two lunch portions, and frittata is one of the few things here that is arguably better cold.',
  },

  'creamy-chicken-rice': {
    name: 'Creamy Garlic Chicken and Rice',
    kind: 'dinner',
    tagline: 'One pan, with the rice cooked in the stock rather than in water. Do not lift the lid while it cooks.',
    time: '40 min',
    timeMins: 40,
    yield: 4,
    // The one dish in the book whose rice cannot be cooked separately: it is
    // steamed in the stock with the chicken. Handled by the next-day rule instead.
    riceNextDay: true,
    ingredients: [
      ing('640g chicken thighs', '640g chicken thigh fillets, in large pieces'),
      ing('300g brown rice dry', '300g brown rice'),
      ing('2 onion', '2 onions, diced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('900ml chicken stock'),
      ing('250g frozen peas'),
      ing('120g low-fat crème fraîche'),
      ing('1 lemon'),
      ing('2 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Brown the chicken in the oil over a high heat until coloured all over, then lift it out.',
      'Cook the onions for 6 minutes, add the garlic and herbs for a minute, then the rice, stirring until every grain is glossy.',
      'Add the stock, return the chicken, bring to the boil, then turn to the lowest heat and put a tight lid on.',
      'Cook 25 minutes without lifting the lid. Stir in the peas, replace the lid, and leave off the heat for 5 minutes.',
      'Stir through the crème fraîche and lemon juice off the heat, check the chicken is cooked through, and season.',
    ],
    swap: 'Natural yogurt instead of crème fraîche, stirred in off the heat so it cannot split.',
    leftovers: 'Two lunch portions, and the one exception in the book: the rice is cooked into the dish, so it cannot be made fresh twice. Portion the leftovers straight away, get them in the fridge within an hour, and eat them tomorrow &mdash; not the day after. Reheat once, until steaming.',
  },

  'sweet-potato-black-bean-chilli': {
    name: 'Sweet Potato and Black Bean Chilli',
    kind: 'dinner',
    tagline: 'The cocoa is not there to make it chocolatey. It is there to make a meat-free chilli taste like it had meat in it.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('800g sweet potato', '800g sweet potatoes, in 2cm dice'),
      ing('480g black beans', '2 x 400g tins black beans, drained'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('2 onion', '2 onions, diced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('30g tomato purée'),
      ing('2 tbsp olive oil'),
      ing('230g brown rice dry', '230g brown rice, cooked fresh'),
      ing('100g low-fat natural yogurt', '100g natural yogurt, to serve'),
      ing(negligible('cumin'), '2 tsp ground cumin'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
      ing(negligible('cocoa powder'), '1 tbsp cocoa powder'),
    ],
    method: [
      'Cook the onions in the oil for 6 minutes, then add the garlic, cumin, paprika and cocoa for a minute.',
      'Stir in the tomato purée for a minute, then add the sweet potato, black beans, tomatoes and 200ml water.',
      'Bring to a simmer, cover, and cook 20 minutes while the rice boils, until the sweet potato crushes against the side of the pan but still holds its shape.',
      'Season hard. A chilli without meat needs noticeably more salt than one with.',
      'Serve on the rice with a spoon of yogurt.',
    ],
    swap: 'Butternut squash instead of sweet potato. Frozen squash chunks skip the peeling entirely.',
    leftovers: 'Two lunch portions. Boil rice fresh tomorrow rather than keeping tonight’s.',
  },

  'turkey-burgers-wedges': {
    name: 'Turkey Burgers with Paprika Wedges',
    kind: 'dinner',
    tagline: 'Lean mince needs help to stay juicy, so grated onion goes into the patty and the salt goes on the outside.',
    time: '40 min',
    timeMins: 40,
    yield: 4,
    ingredients: [
      ing('600g turkey mince lean'),
      ing('1 onion', '1 onion, coarsely grated'),
      ing('1 egg'),
      ing('40g rolled oats', '40g porridge oats'),
      ing('800g potato', '800g potatoes, cut into wedges'),
      ing('4 wholemeal roll', '4 wholemeal rolls'),
      ing('100g mixed leaves'),
      ing('150g tomatoes', '1 large tomato, sliced'),
      ing('40g light mayo'),
      ing('2 tbsp olive oil'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Toss the wedges in 2 tbsp of the oil, the paprika and plenty of salt, spread them in one layer and roast 30 minutes, turning once.',
      'Squeeze the grated onion in your hand over the sink to get the water out, then mix it with the turkey mince, egg, oats, salt and pepper.',
      'Shape four patties wider than the rolls, since they shrink, and press a dent into the middle of each so they stay flat.',
      'Fry in the last of the oil over a medium-high heat for 5&ndash;6 minutes a side, until cooked through with no pink in the middle.',
      'Toast the rolls and build with mayonnaise, leaves and tomato.',
    ],
    swap: 'Beef mince makes a juicier burger and needs no oats to hold it together.',
    leftovers: 'Two patties and the extra wedges. Reheat the patties in the oven rather than the microwave.',
  },

  'bean-tomato-stew': {
    name: 'Butter Bean and Tomato Stew with Garlic Toast',
    kind: 'dinner',
    tagline: 'Store-cupboard food that eats like a proper dinner, mostly because of what happens to the bread.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('720g cannellini beans', '3 x 400g tins cannellini or butter beans, drained'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('2 onion', '2 onions, diced'),
      ing('3 carrot', '3 carrots, diced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('200g spinach', '200g frozen spinach'),
      ing('30g tomato purée'),
      ing('400ml vegetable stock'),
      ing('4 tbsp olive oil'),
      ing('6 slices wholemeal bread', '6 thick slices bread'),
      ing('80g parmesan', '80g hard cheese, grated'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Cook the onions and carrots in 2 tbsp of the oil for 10 minutes with a good pinch of salt.',
      'Add two thirds of the garlic and the herbs for a minute, then the tomato purée for another.',
      'Add the beans, tomatoes and stock and simmer 12 minutes, crushing a few beans against the side of the pan to thicken it.',
      'Stir in the frozen spinach for the last 3 minutes and season well.',
      'Toast the bread, rub each slice with the remaining raw garlic, trickle over the last of the oil and top with the cheese.',
    ],
    swap: 'Any large white bean. Chickpeas work but stay firmer.',
    leftovers: 'Two lunch portions of the stew. Toast the bread fresh on the day.',
  },

  'curried-chickpea-potato-traybake': {
    name: 'Curried Chickpea and Potato Traybake',
    kind: 'dinner',
    tagline: 'Everything roasts on one tray and the yogurt goes on at the table. Almost no standing over it.',
    time: '40 min',
    timeMins: 40,
    yield: 4,
    ingredients: [
      ing('800g potato', '800g potatoes, in 2cm dice'),
      ing('480g tinned chickpeas', '2 x 400g tins chickpeas, drained'),
      ing('2 onion', '2 red onions, in wedges'),
      ing('300g peppers', '2 peppers, in chunks'),
      ing('200g spinach', '200g frozen spinach'),
      ing('3 tbsp olive oil'),
      ing('16g curry powder', '2 tbsp curry powder'),
      ing('200g low-fat natural yogurt'),
      ing('3 wholemeal pitta', '3 wholemeal pittas'),
      ing('1 lemon'),
      ing(negligible('turmeric'), '1 tsp turmeric'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Toss the potatoes with half the oil, half the curry powder, the turmeric and plenty of salt, and roast on a large tray for 18 minutes.',
      'Toss the chickpeas, onions and peppers with the rest of the oil and curry powder.',
      'Add them to the tray, stir everything together, and roast another 15 minutes until the potatoes are crisp at the edges and the chickpeas have started to pop.',
      'Stir the frozen spinach through the hot tray and give it 3 minutes to wilt.',
      'Squeeze over the lemon, season, and serve with yogurt and warm pitta.',
    ],
    swap: 'Sweet potato instead of half the white potato, which needs about five minutes less.',
    leftovers: 'Two lunch portions. Keep the yogurt separate until you eat it.',
  },
};
