#!/usr/bin/env node
// Admin QA workflow CLI — the "Add finding" / "Recheck plan" / assessment
// and status actions from the plan-quality QA workflow. This mirrors the
// rest of the QA tooling in this repo (npm run qa:semantic etc.): it reads
// and writes committed JSON under docs/semantic-qa/, so changes go through
// the normal build/deploy flow rather than a live database write — there is
// no server-side write path for this data, matching how semanticQaDashboard.js
// itself is already generated by a script rather than edited live.
//
// Usage:
//   node scripts/qa-admin.js add-finding --route /plans/x --category "Shopping list" \
//     --severity Medium --note "..." [--evidence "..."] [--location "Tuesday — Lunch"]
//   node scripts/qa-admin.js set-status <findingId> <New|Investigating|Fixed|Accepted>
//   node scripts/qa-admin.js set-assessment <findingId> <"True issue"|"Useful warning"|"False positive"|Uncertain> [--note "..."]
//   node scripts/qa-admin.js recheck <route>
//   node scripts/qa-admin.js list [--route /plans/x] [--status New] [--assessment Uncertain]
import {
  recheckPlanRoute,
  writeSemanticQaDashboard,
} from './lib/semanticPlanQa.js';
import {
  FINDING_CATEGORIES,
  HUMAN_ASSESSMENTS,
  WORKFLOW_STATUSES,
  addManualFinding,
  ledgerRows,
  readLedger,
  setFindingAssessment,
  setFindingStatus,
  setPotentiallySystemic,
  writeLedger,
} from './lib/semanticQaLedger.js';
import { readDeploymentLog, recordDeployment, writeDeploymentLog } from './lib/qaDeploymentLog.js';

const [, , command, ...rest] = process.argv;

try {
  switch (command) {
    case 'add-finding': await runAddFinding(rest); break;
    case 'set-status': await runSetStatus(rest); break;
    case 'set-assessment': await runSetAssessment(rest); break;
    case 'flag-systemic': await runFlagSystemic(rest); break;
    case 'recheck': await runRecheck(rest); break;
    case 'list': runList(rest); break;
    case 'record-deployment': runRecordDeployment(rest); break;
    default: printUsageAndExit();
  }
} catch (error) {
  console.error(`qa-admin: ${error.message || error}`);
  process.exit(1);
}

async function runAddFinding(args) {
  const flags = parseFlags(args);
  if (!flags.route || !flags.category || !flags.severity) {
    throw new Error('add-finding requires --route, --category and --severity.');
  }
  const ledger = readLedger();
  const { ledger: nextLedger, id } = addManualFinding(ledger, {
    route: flags.route,
    category: flags.category,
    severity: flags.severity,
    note: flags.note || '',
    evidence: flags.evidence || flags.note || '',
    dayOrMeal: flags.location || '',
    potentiallySystemic: Boolean(flags.systemic),
  });
  writeLedger(nextLedger);
  await regenerateDashboard(nextLedger);
  console.log(`Added finding ${id} for ${flags.route} (${flags.category}, ${flags.severity})${flags.systemic ? ' [potentially systemic]' : ''}.`);
}

async function runFlagSystemic(args) {
  const flags = parseFlags(args);
  const [findingId] = args.filter(value => !value.startsWith('--'));
  if (!findingId) throw new Error('flag-systemic requires <findingId> [--off].');
  const nextLedger = setPotentiallySystemic(readLedger(), findingId, !flags.off);
  writeLedger(nextLedger);
  await regenerateDashboard(nextLedger);
  console.log(`${findingId} -> potentially systemic: ${!flags.off}`);
}

function runRecordDeployment(args) {
  const flags = parseFlags(args);
  if (!flags.commit) throw new Error('record-deployment requires --commit <hash> [--summary "..."] [--gate "..."].');
  const log = recordDeployment(readDeploymentLog(), {
    commit: flags.commit,
    summary: flags.summary || '',
    gate: flags.gate || '',
  });
  writeDeploymentLog(log);
  const entry = log.deployments[log.deployments.length - 1];
  console.log(`Recorded deployment ${entry.commit} at ${entry.deployedAt}.`);
}

async function runSetStatus(args) {
  const [findingId, status] = args;
  if (!findingId || !status) throw new Error('set-status requires <findingId> <status>.');
  const nextLedger = setFindingStatus(readLedger(), findingId, status);
  writeLedger(nextLedger);
  await regenerateDashboard(nextLedger);
  console.log(`${findingId} -> status: ${status}`);
}

async function runSetAssessment(args) {
  const flags = parseFlags(args);
  const [findingId, assessment] = args.filter(value => !value.startsWith('--'));
  if (!findingId || !assessment) throw new Error('set-assessment requires <findingId> <assessment>.');
  const nextLedger = setFindingAssessment(readLedger(), findingId, assessment, flags.note || '');
  writeLedger(nextLedger);
  await regenerateDashboard(nextLedger);
  console.log(`${findingId} -> assessment: ${assessment}`);
}

async function runRecheck(args) {
  const [route] = args;
  if (!route) throw new Error('recheck requires <route>, e.g. /plans/aldi-high-protein-low-cal-1500.');
  const { ledger, result } = recheckPlanRoute(route);
  await regenerateDashboard(ledger);
  if (result.status === 'unable-to-determine') {
    console.log(`Unable to determine: ${result.error}`);
    return;
  }
  console.log(
    `Rechecked ${route}: ${result.stillDetected} still detected, `
    + `${result.noLongerDetected} no longer detected, ${result.newFindings} new.`,
  );
}

function runList(args) {
  const flags = parseFlags(args);
  const rows = ledgerRows(readLedger()).filter(row => (
    (!flags.route || row.route === flags.route)
    && (!flags.status || row.status === flags.status)
    && (!flags.assessment || row.humanAssessment === flags.assessment)
  ));
  for (const row of rows) {
    console.log([
      row.id, row.route, row.severity, row.category, row.status, row.humanAssessment,
      row.potentiallySystemic ? 'SYSTEMIC' : '',
      row.resolvedAt ? `resolved ${row.resolvedAt.slice(0, 10)}` : 'open',
    ].filter(Boolean).join(' | '));
  }
  console.log(`${rows.length} finding(s).`);
}

// Refreshes only the ledger-derived parts of src/data/semanticQaDashboard.js
// (findingsLedger, and the status/assessment shown against each recent
// finding) against the already-generated dashboard, rather than rebuilding
// it from scratch — recentFindings/breakdowns/trend only exist in full for
// the last real weekly sample (history.json intentionally does not retain
// full per-finding evidence between runs), so a full rebuild here would
// silently blank them out. A full `npm run qa:semantic` re-sample is the
// separate, heavier weekly job that legitimately replaces those.
async function regenerateDashboard(ledger) {
  const existing = await readExistingDashboard();
  const ledgerEntries = ledger.entries || {};
  writeSemanticQaDashboard({
    ...existing,
    recentFindings: (existing.recentFindings || []).map(item => ({
      ...item,
      reviewStatus: ledgerEntries[item.id]?.status || item.reviewStatus,
      humanAssessment: ledgerEntries[item.id]?.humanAssessment || item.humanAssessment || 'Uncertain',
    })),
    findingsLedger: ledgerRows(ledger).slice(0, 200).map(entry => ({
      id: entry.id,
      source: entry.source,
      route: entry.route,
      category: entry.category,
      severity: entry.severity,
      evidence: entry.evidence,
      affectedLocation: entry.affectedLocation,
      firstDetectedAt: entry.firstDetectedAt,
      lastDetectedAt: entry.lastDetectedAt,
      lastRecheckAt: entry.lastRecheckAt,
      lastRecheckResult: entry.lastRecheckResult,
      resolvedAt: entry.resolvedAt,
      status: entry.status,
      humanAssessment: entry.humanAssessment,
      humanNote: entry.humanNote,
      potentiallySystemic: entry.potentiallySystemic || false,
    })),
  });
}

async function readExistingDashboard() {
  try {
    const mod = await import(`../src/data/semanticQaDashboard.js?t=${Date.now()}`);
    return mod.SEMANTIC_QA_DASHBOARD;
  } catch {
    return { available: false, latest: null, trend: [], recentFindings: [], findingsLedger: [] };
  }
}

function parseFlags(values) {
  const flags = {};
  for (let index = 0; index < values.length; index += 1) {
    const raw = values[index];
    if (!raw.startsWith('--')) continue;
    const name = raw.slice(2);
    const next = values[index + 1];
    if (next && !next.startsWith('--')) {
      flags[name] = next;
      index += 1;
    } else flags[name] = true;
  }
  return flags;
}

function printUsageAndExit() {
  console.log([
    'Usage: node scripts/qa-admin.js <command> [args]',
    '',
    'Commands:',
    '  add-finding --route <route> --category <category> --severity <Critical|High|Medium|Low> --note <text> [--evidence <text>] [--location <text>] [--systemic]',
    `      categories: ${FINDING_CATEGORIES.join(', ')}`,
    '  set-status <findingId> <status>',
    `      statuses: ${WORKFLOW_STATUSES.join(', ')}`,
    '  set-assessment <findingId> <assessment> [--note <text>]',
    `      assessments: ${HUMAN_ASSESSMENTS.join(', ')}`,
    '  flag-systemic <findingId> [--off]',
    '      marks (or unmarks) a finding as worth a library-wide investigation, independent of status/assessment',
    '  recheck <route>',
    '  list [--route <route>] [--status <status>] [--assessment <assessment>]',
    '  record-deployment --commit <hash> [--summary <text>] [--gate <text>]',
  ].join('\n'));
  process.exit(1);
}
