// Lidl Budget - dinners 13-24.

import { negligible } from '../../build/plan.mjs';

const ing = (line, display) => ({ line, display: display || line });

export const dinnersB = {
  'quorn-bolognese': {
    name: 'Meat-Free Bolognese',
    kind: 'dinner',
    tagline: 'The milk step is what makes a quick sauce taste like a slow one, and it matters more without meat than with it.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('400g quorn mince', '400g meat-free mince'),
      ing('300g mushrooms', '300g mushrooms, finely chopped'),
      ing('2 onion', '2 onions, finely diced'),
      ing('2 carrot', '2 carrots, finely diced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('150ml semi-skimmed milk'),
      ing('30g tomato purée'),
      ing('300g wholemeal pasta dry', '300g spaghetti'),
      ing('60g parmesan', '60g hard cheese, grated'),
      ing('3 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Brown the mushrooms hard in 2 tbsp of the oil for 8 minutes without stirring much, until they have given up their water and coloured.',
      'Add the rest of the oil with the onion and carrot and cook 8 minutes, then the garlic and herbs for a minute and the tomato pur&eacute;e for another.',
      'Add the meat-free mince and cook 3 minutes, then pour in the milk and simmer until it has almost disappeared.',
      'Add the tomatoes with a splash of water and simmer 12 minutes while the pasta boils.',
      'Season hard &mdash; a sauce without meat needs noticeably more salt &mdash; and finish with the cheese.',
    ],
    swap: 'Green lentils, or half mince and half lentils.',
    leftovers: 'Two lunch portions, and better tomorrow than tonight.',
  },

  'cod-tomato-olive-couscous': {
    name: 'Cod in Tomato and Olive Sauce',
    kind: 'dinner',
    tagline: 'The fish poaches in the sauce, so there is nothing to turn and nothing to overcook while your back is turned.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('640g cod fillet', '640g cod fillets, defrosted'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('120g olives', '120g olives, halved'),
      ing('2 onion', '2 onions, sliced'),
      ing('6 cloves garlic', '6 cloves garlic, sliced'),
      ing('280g wholemeal couscous dry', '280g couscous'),
      ing('450ml vegetable stock'),
      ing('250g green beans'),
      ing('30g tomato purée'),
      ing('3 tbsp olive oil'),
      ing('1 lemon'),
    ],
    method: [
      'Cook the onions in the oil in a wide pan for 8 minutes, then the garlic for a minute and the tomato pur&eacute;e for another.',
      'Add the tomatoes and olives with a pinch of sugar and salt and simmer 8 minutes until thickened.',
      'Pour the hot stock over the couscous, cover with a plate and leave 8 minutes, then fork it through.',
      'Lay the cod fillets into the sauce, scatter the green beans around them, lid the pan and cook 8&ndash;10 minutes on a low heat until the fish is opaque and flakes under a fork.',
      'Squeeze over the lemon and serve on the couscous.',
    ],
    swap: 'Any white fish. Frozen fillets are fine &mdash; defrost them in the fridge overnight, not on the worktop.',
    leftovers: 'Two lunch portions. Warm it gently; fish toughens on a hard second heating.',
  },

  'sweet-potato-lentil-curry': {
    name: 'Sweet Potato and Red Lentil Curry',
    kind: 'dinner',
    tagline: 'The lentils dissolve into the sauce and the sweet potato holds its shape. Together they do the job coconut milk usually does.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('700g sweet potato', '700g sweet potatoes, in 2cm dice'),
      ing('200g red lentils dry', '200g red lentils, rinsed'),
      ing('400g tinned tomatoes', '1 x 400g tin chopped tomatoes'),
      ing('200ml coconut milk light'),
      ing('2 onion', '2 onions, diced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('20g ginger', '1 thumb ginger, grated'),
      ing('800ml vegetable stock'),
      ing('200g spinach', '200g frozen spinach'),
      ing('16g curry powder', '2 tbsp curry powder'),
      ing('2 tbsp olive oil'),
      ing('4 wholemeal pitta', '4 flatbreads'),
    ],
    method: [
      'Cook the onions in the oil for 8 minutes, then add the garlic, ginger and curry powder for a minute.',
      'Add the sweet potato, lentils, tomatoes and stock. Bring to the boil, then simmer 20 minutes, stirring every few minutes so the lentils do not catch on the base.',
      'It is ready when the lentils have collapsed and the sweet potato crushes against the pan but still holds its shape.',
      'Stir in the coconut milk and the frozen spinach and warm through for 3 minutes.',
      'Season hard and serve with warm flatbread.',
    ],
    swap: 'Butternut squash. Frozen squash chunks skip the peeling entirely.',
    leftovers: 'Two lunch portions. It thickens overnight; loosen with boiling water.',
  },

  'chickpea-spinach-pasta': {
    name: 'Chickpea, Spinach and Lemon Pasta',
    kind: 'dinner',
    tagline: 'Crushing half the chickpeas thickens the sauce and leaves the rest whole for texture. Fifteen minutes of actual work.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('480g tinned chickpeas', '2 x 400g tins chickpeas, drained'),
      ing('300g wholemeal pasta dry', '300g pasta'),
      ing('250g spinach', '250g frozen spinach'),
      ing('6 cloves garlic', '6 cloves garlic, sliced'),
      ing('1 onion', '1 onion, finely diced'),
      ing('80g parmesan', '80g hard cheese, grated'),
      ing('1 lemon'),
      ing('3 tbsp olive oil'),
      ing('40g mixed seeds', '40g mixed seeds, toasted'),
      ing(negligible('chilli flakes'), 'chilli flakes, to taste'),
    ],
    method: [
      'Get the pasta on in well-salted water.',
      'Cook the onion in 3 tbsp of the oil for 6 minutes, then the garlic and chilli flakes for a minute.',
      'Add the chickpeas and crush about half of them against the side of the pan with a wooden spoon. Add a ladle of pasta water and let it bubble into a loose sauce.',
      'Stir in the frozen spinach and cook 3 minutes.',
      'Drain the pasta and toss it through with the lemon juice, the cheese and the rest of the oil. Scatter the toasted seeds over.',
    ],
    swap: 'Butter beans instead of chickpeas; they crush more readily and go creamier.',
    leftovers: 'Two lunch portions, and good cold with extra lemon.',
  },

  'turkey-meatball-orzo': {
    name: 'Turkey Meatballs with Orzo',
    kind: 'dinner',
    tagline: 'The orzo cooks in the sauce with the meatballs, so the whole dinner is one pan and one chopping board.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('500g turkey mince lean'),
      ing('40g rolled oats', '40g porridge oats'),
      ing('1 egg'),
      ing('1 onion', '1 onion, finely diced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('260g orzo pasta dry', '260g orzo'),
      ing('500ml chicken stock'),
      ing('200g spinach', '200g frozen spinach'),
      ing('60g parmesan', '60g hard cheese, grated'),
      ing('2 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Mix the turkey mince with the oats, egg, half the garlic, half the herbs, salt and pepper, and roll into about 20 small balls.',
      'Brown them in the oil in a wide pan, turning, for 6 minutes. They need not be cooked through yet. Lift them out.',
      'Cook the onion 5 minutes, add the remaining garlic and herbs for a minute, then the tomatoes, stock and orzo.',
      'Return the meatballs, simmer 12 minutes, stirring occasionally so the orzo does not stick, until it is tender and the meatballs are cooked through.',
      'Stir in the frozen spinach for the last 3 minutes and finish with the cheese.',
    ],
    swap: 'Beef or pork mince, which need no oats to hold together.',
    leftovers: 'Two lunch portions. The orzo drinks the sauce overnight; add a splash of water.',
  },

  'mushroom-leek-cannellini-pasta': {
    name: 'Mushroom, Leek and White Bean Pasta',
    kind: 'dinner',
    tagline: 'No cream and no cheese sauce: the beans blitzed into the pasta water do it instead.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('400g mushrooms', '400g mushrooms, sliced'),
      ing('300g leek', '2 leeks, sliced'),
      ing('480g cannellini beans', '2 x 400g tins cannellini beans, drained'),
      ing('300g wholemeal pasta dry', '300g pasta'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('60g parmesan', '60g hard cheese, grated'),
      ing('1 lemon'),
      ing('4 tbsp olive oil'),
      ing('150g frozen peas'),
      ing(negligible('black pepper'), 'plenty of black pepper'),
    ],
    method: [
      'Get the pasta on, adding the peas for the last 2 minutes.',
      'Brown the mushrooms hard in 2 tbsp of the oil for 8 minutes, stirring rarely.',
      'Add the rest of the oil with the leeks and cook 6 minutes, then the garlic for a minute.',
      'Crush half the beans with a fork, add all of them to the pan with a big ladle of pasta water, and simmer 3 minutes until it loosens into a sauce.',
      'Drain the pasta and toss it through with the lemon juice, the cheese and a great deal of pepper.',
    ],
    swap: 'Butter beans crush more easily and give a smoother sauce.',
    leftovers: 'Two lunch portions. Loosen with a splash of water when reheating.',
  },

  'veg-chickpea-tagine': {
    name: 'Vegetable and Chickpea Tagine',
    kind: 'dinner',
    tagline: 'Cinnamon and cumin with the tomatoes, and dried fruit if you have it. It tastes like it took two hours and takes thirty-five minutes.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('480g tinned chickpeas', '2 x 400g tins chickpeas, drained'),
      ing('500g butternut squash', '500g butternut squash, in 2cm dice'),
      ing('2 carrot', '2 carrots, in thick slices'),
      ing('2 onion', '2 onions, sliced'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('60g raisins'),
      ing('280g wholemeal couscous dry', '280g couscous'),
      ing('450ml vegetable stock'),
      ing('30g tomato purée'),
      ing('3 tbsp olive oil'),
      ing('150g low-fat natural yogurt', '150g natural yogurt, to serve'),
      ing(negligible('cumin'), '2 tsp cumin'),
      ing(negligible('cinnamon'), '1 tsp cinnamon'),
    ],
    method: [
      'Cook the onions in the oil for 8 minutes, then add the cumin and cinnamon for a minute and the tomato pur&eacute;e for another.',
      'Add the squash, carrots, chickpeas, tomatoes, raisins and 200ml water. Simmer, covered, for 20 minutes until the squash is tender.',
      'Pour the hot stock over the couscous, cover with a plate for 8 minutes, then fork it through.',
      'Season the tagine well and serve on the couscous with a spoon of yogurt.',
    ],
    swap: 'Sweet potato instead of squash. Dried apricots instead of raisins if they are on offer.',
    leftovers: 'Two lunch portions, and noticeably better on the second day.',
  },

  'spiced-bean-burgers': {
    name: 'Spiced Bean Burgers',
    kind: 'dinner',
    tagline: 'Drying the beans properly before mashing is the entire difference between a burger and a bean paste.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('480g kidney beans', '2 x 400g tins kidney beans, drained and dried'),
      ing('240g black beans', '1 x 400g tin black beans, drained and dried'),
      ing('1 onion', '1 onion, very finely diced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('50g rolled oats', '50g porridge oats'),
      ing('1 egg'),
      ing('700g potato', '700g potatoes, in wedges'),
      ing('4 wholemeal roll', '4 rolls'),
      ing('100g mixed leaves'),
      ing('40g light mayo'),
      ing('3 tbsp olive oil'),
      ing(negligible('cumin'), '2 tsp cumin'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Toss the wedges with 2 tbsp of the oil and salt and roast 30 minutes, turning once.',
      'Tip the drained beans onto a tea towel and pat them properly dry, then mash them with a fork, stopping while there are still whole pieces.',
      'Mix in the onion, garlic, oats, egg, cumin, paprika, salt and pepper, and shape four firm patties. If the mix will not hold, add another spoon of oats.',
      'Fry in the rest of the oil over a medium heat for 4&ndash;5 minutes a side until deeply browned and crisp; they need a proper crust to hold together.',
      'Build in the rolls with the mayonnaise and leaves, wedges alongside.',
    ],
    swap: 'Any tinned beans. Chickpeas make a firmer, drier patty.',
    leftovers: 'Two patties and the spare wedges. Reheat the patties in the oven, not the microwave.',
  },

  'cauliflower-chickpea-tray': {
    name: 'Roasted Cauliflower and Chickpea Tray',
    kind: 'dinner',
    tagline: 'Cauliflower roasted hard until the edges blacken is a different vegetable from cauliflower boiled. Do not crowd the tray.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('800g cauliflower', '1 large cauliflower, in florets'),
      ing('480g tinned chickpeas', '2 x 400g tins chickpeas, drained'),
      ing('2 onion', '2 red onions, in wedges'),
      ing('450g potato', '450g potatoes, in 2cm dice'),
      ing('250g low-fat natural yogurt'),
      ing('3 tbsp olive oil'),
      ing('1 lemon'),
      ing('40g mixed seeds'),
      ing('4 wholemeal pitta', '4 flatbreads'),
      ing(negligible('cumin'), '2 tsp cumin'),
      ing(negligible('turmeric'), '1 tsp turmeric'),
    ],
    method: [
      'Heat the oven to 220&deg;C fan. Toss the potatoes and cauliflower with 3 tbsp of the oil, the cumin, turmeric and plenty of salt.',
      'Spread over two trays &mdash; crowded, cauliflower steams and goes grey &mdash; and roast 20 minutes.',
      'Add the chickpeas and onions, toss, and roast 12 minutes more until the cauliflower edges have caught and the chickpeas have started to pop.',
      'Stir the lemon juice and the rest of the oil into the yogurt with a pinch of salt.',
      'Scatter the seeds over the tray and serve with the yogurt and warm flatbread.',
    ],
    swap: 'Broccoli roasts the same way in about five minutes less.',
    leftovers: 'Two lunch portions, good cold. Keep the yogurt separate.',
  },

  'mackerel-potato-hash': {
    name: 'Smoked Mackerel and Potato Hash',
    kind: 'dinner',
    tagline: 'Smoked mackerel is already cooked, so this is really a potato recipe with something good folded through at the end.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('300g smoked mackerel fillet', '300g smoked mackerel fillets, skin off'),
      ing('900g potato', '900g potatoes, in 2cm dice'),
      ing('300g leek', '2 leeks, sliced'),
      ing('250g frozen peas'),
      ing('200g low-fat natural yogurt'),
      ing('3 tsp mustard'),
      ing('1 lemon'),
      ing('4 spring onion', '4 spring onions, sliced'),
      ing('3 tbsp olive oil'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Boil the diced potatoes for 8 minutes, then drain them and let the steam die down &mdash; wet potatoes will not crisp.',
      'Fry them in the oil in a wide pan over a high heat for 8 minutes, turning only occasionally so they colour.',
      'Add the leeks and cook 6 minutes, then the peas for 2 more.',
      'Flake the mackerel in large pieces, checking for bones, and fold it through gently at the end so the flakes stay whole.',
      'Mix the yogurt with the mustard and lemon juice, spoon it over, and finish with the spring onions and plenty of pepper.',
    ],
    swap: 'Tinned mackerel or salmon, folded in the same way.',
    leftovers: 'Two lunch portions, good cold or warmed gently.',
  },

  'greek-style-bean-bake': {
    name: 'Baked Beans with Feta and Herbs',
    kind: 'dinner',
    tagline: 'Beans baked in tomato until the top catches, with feta crumbled on at the end so it keeps its edges.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('720g cannellini beans', '3 x 400g tins butter beans, drained'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('2 onion', '2 onions, sliced'),
      ing('3 carrot', '3 carrots, diced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('150g reduced-fat feta', '150g feta, crumbled'),
      ing('30g tomato purée'),
      ing('4 tbsp olive oil'),
      ing('4 slices sourdough bread', '4 thick slices of bakery bread'),
      ing('200g mixed leaves', 'salad, to serve'),
      ing(negligible('mixed herbs'), '2 tsp dried oregano or mixed herbs'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Cook the onions and carrots in 3 tbsp of the oil in an ovenproof pan for 10 minutes.',
      'Add the garlic and herbs for a minute, then the tomato pur&eacute;e for another.',
      'Add the beans and tomatoes with a pinch of sugar and a good pinch of salt, and simmer 5 minutes.',
      'Transfer to the oven, uncovered, for 15 minutes, until the top has darkened and caught in places.',
      'Crumble the feta over, trickle on the last of the oil, and serve with bread and a plain salad.',
    ],
    swap: 'Any large white bean. A tin of chickpeas for one of the beans adds texture.',
    leftovers: 'Two lunch portions. Add the feta fresh rather than reheating it.',
  },

  'veg-fried-rice': {
    name: 'Vegetable and Egg Fried Rice',
    kind: 'dinner',
    tagline: 'The Sunday dinner, cooked at half size. The pan has to be hotter than feels reasonable.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('270g brown rice dry', '270g brown rice, cooked and cooled'),
      ing('8 egg', '8 eggs, beaten'),
      ing('300g frozen peas'),
      ing('2 carrot', '2 carrots, finely diced'),
      ing('300g cabbage', '300g cabbage, shredded'),
      ing('6 spring onion', '6 spring onions, sliced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('20g ginger', '1 thumb ginger, grated'),
      ing('4 tbsp soy sauce'),
      ing('2 tbsp sesame oil'),
      ing('2 tbsp olive oil'),
    ],
    method: [
      'Boil the rice, drain it and spread it on a tray to cool quickly while you prepare everything else. Cold dry rice fries; warm rice steams into paste.',
      'Get a large pan very hot. Add the olive oil and the beaten egg, scramble hard for 30 seconds, and tip it onto a plate.',
      'Stir-fry the carrots and cabbage for 4 minutes, then the garlic, ginger and the white of the spring onions for 30 seconds.',
      'Add the rice and press it flat, leaving it 30 seconds at a time between stirs so it catches and crisps. Add the peas and toss 2 minutes.',
      'Return the egg, add the soy round the edge of the pan rather than into the middle, and finish with the sesame oil and green spring onion.',
    ],
    swap: 'Any quick-cooking vegetable. Firm tofu, browned first, if you want more from it.',
    leftovers: 'None, by design. It is cooked at half size on a Sunday and eaten the same night &mdash; cooked rice is reheated once only, and frying it was that once.',
  },
};
