// Lidl Budget - dinners 1-12.
//
// Roughly half these dinners are meat-free, which is the single biggest lever on
// a discounter food bill and the reason this book reads differently from the
// Aldi budget edition. Where meat appears it is doing a specific job rather than
// being the default centre of the plate.

import { negligible } from '../../build/plan.mjs';

const ing = (line, display) => ({ line, display: display || line });

export const dinnersA = {
  'tofu-peanut-noodles': {
    name: 'Tofu and Peanut Noodles',
    kind: 'dinner',
    tagline: 'Peanut butter, soy and lime make a sauce in the time the noodles boil. Press the tofu first or it will not brown.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('450g firm tofu', '450g firm tofu, pressed and cubed'),
      ing('280g wholewheat noodles dry', '280g noodles'),
      ing('300g cabbage', '300g cabbage, shredded'),
      ing('2 carrot', '2 carrots, in matchsticks'),
      ing('300g peppers', '2 peppers, sliced'),
      ing('60g peanut butter'),
      ing('4 tbsp soy sauce'),
      ing('1 tbsp honey'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('1 lemon', '1 lime or lemon'),
      ing('2 tbsp olive oil'),
    ],
    method: [
      'Press the tofu between two plates under something heavy while you chop everything else. Ten minutes is enough and it is the difference between browning and steaming.',
      'Whisk the peanut butter, soy, honey and lemon juice with 100ml of hot water until it pours.',
      'Boil the noodles, drain and toss with a drop of oil.',
      'Brown the tofu in the oil in a very hot pan, leaving each side alone for a minute or two until it is gold on several faces, then lift it out.',
      'Stir-fry the cabbage, carrots and peppers for 4 minutes, add the garlic for 30 seconds, then return the tofu and noodles and pour the sauce over. Toss until everything is coated.',
    ],
    swap: 'Chicken thigh, or a tin of chickpeas browned in the same way.',
    leftovers: 'Two lunch portions. The sauce thickens overnight; loosen with a spoon of hot water.',
  },

  'chana-potato-curry': {
    name: 'Chickpea and Potato Curry',
    kind: 'dinner',
    tagline: 'Two tins and a bag of potatoes. The potatoes break down slightly at the edges and thicken the sauce, which is the whole trick.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('700g potato', '700g potatoes, in 2cm dice'),
      ing('480g tinned chickpeas', '2 x 400g tins chickpeas, drained'),
      ing('400g tinned tomatoes', '1 x 400g tin chopped tomatoes'),
      ing('2 onion', '2 onions, sliced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('20g ginger', '1 thumb ginger, grated'),
      ing('250g spinach', '250g frozen spinach'),
      ing('30g tomato purée'),
      ing('16g curry powder', '2 tbsp curry powder'),
      ing('2 tbsp olive oil'),
      ing('4 wholemeal pitta', '4 flatbreads'),
      ing('150g low-fat natural yogurt', '150g natural yogurt, to serve'),
    ],
    method: [
      'Cook the onions in the oil for 8 minutes until soft and gold at the edges.',
      'Add the garlic, ginger and curry powder for a minute, then the tomato purée for another.',
      'Add the potatoes, chickpeas, tomatoes and 300ml water. Bring to a simmer, cover, and cook 20 minutes until the potatoes are soft enough to crush against the pan.',
      'Stir in the frozen spinach for the last 3 minutes and season generously.',
      'Serve with warm flatbread and a spoon of yogurt.',
    ],
    swap: 'Sweet potato, which needs about five minutes less. Butter beans instead of one chickpea tin.',
    leftovers: 'Two lunch portions, and better on the second day once the spices have settled.',
  },

  'white-bean-rosemary-stew': {
    name: 'White Bean Stew with Garlic Toast',
    kind: 'dinner',
    tagline: 'Three tins of beans and a good loaf. Crushing some of the beans against the side of the pan is what turns soup into stew.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('720g cannellini beans', '3 x 400g tins cannellini or butter beans, drained'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('2 onion', '2 onions, diced'),
      ing('3 carrot', '3 carrots, diced'),
      ing('2 sticks celery', '2 sticks celery, diced'),
      ing('8 cloves garlic', '8 cloves garlic, 6 crushed and 2 whole'),
      ing('400ml vegetable stock'),
      ing('200g cabbage', '200g cabbage or kale, shredded'),
      ing('30g tomato purée'),
      ing('6 slices sourdough bread', '6 thick slices of bakery bread'),
      ing('4 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs or rosemary'),
    ],
    method: [
      'Cook the onion, carrot and celery in 2 tbsp of the oil for 10 minutes with a good pinch of salt. This is where the flavour comes from and there is no way to add it later.',
      'Add the crushed garlic and herbs for a minute, then the tomato purée for another.',
      'Add the beans, tomatoes and stock and simmer 12 minutes, crushing a third of the beans against the side of the pan as it goes.',
      'Stir in the cabbage for the last 4 minutes and season hard.',
      'Toast the bread, rub each slice with a cut clove of raw garlic and trickle over the last of the oil.',
    ],
    swap: 'Any large white bean. Chickpeas work but stay firm rather than collapsing.',
    leftovers: 'Two lunch portions. Toast fresh bread on the day rather than keeping it.',
  },

  'mushroom-orzo': {
    name: 'Mushroom and Leek Orzo',
    kind: 'dinner',
    tagline: 'Risotto behaviour without the twenty minutes of stirring. Brown the mushrooms properly and it tastes like it took longer.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('500g mushrooms', '500g mushrooms, sliced'),
      ing('300g leek', '2 leeks, sliced'),
      ing('340g orzo pasta dry', '340g orzo'),
      ing('900ml vegetable stock'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('80g parmesan', '80g hard cheese, grated'),
      ing('150g frozen peas'),
      ing('1 lemon'),
      ing('3 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Brown the mushrooms hard in 2 tbsp of the oil for 8 minutes, stirring rarely. They will release water first and then start to colour; the colour is the point.',
      'Add the rest of the oil with the leeks and cook 6 minutes, then the garlic and herbs for a minute.',
      'Stir in the orzo until coated, add the stock, and simmer 12 minutes, stirring now and then so it does not catch.',
      'Add the peas for the last 3 minutes.',
      'Off the heat, stir in the cheese and the lemon juice and season well.',
    ],
    swap: 'Any small pasta shape. A handful of dried mushrooms soaked in the stock deepens it for pennies.',
    leftovers: 'Two lunch portions. It sets firm; loosen with a splash of water when reheating.',
  },

  'quorn-cottage-pie': {
    name: 'Meat-Free Cottage Pie',
    kind: 'dinner',
    tagline: 'Under the grill rather than in the oven, which is what brings it in under forty minutes.',
    time: '40 min',
    timeMins: 40,
    yield: 4,
    ingredients: [
      ing('400g quorn mince', '400g meat-free mince'),
      ing('300g mushrooms', '300g mushrooms, finely chopped'),
      ing('2 onion', '2 onions, diced'),
      ing('3 carrot', '3 carrots, diced small'),
      ing('240g lentils cooked', '1 x 400g tin green lentils, drained'),
      ing('600ml vegetable stock'),
      ing('30g tomato purée'),
      ing('1 kg potato', '1kg potatoes, peeled and quartered'),
      ing('80ml semi-skimmed milk'),
      ing('20g butter'),
      ing('60g cheddar', '60g cheddar, grated'),
      ing('250g frozen peas'),
      ing('2 tbsp olive oil'),
    ],
    method: [
      'Get the potatoes into salted water and boil 18 minutes.',
      'Brown the mushrooms hard in the oil for 6 minutes, then add the onions and carrots and cook 8 minutes more.',
      'Add the tomato pur&eacute;e for a minute, then the meat-free mince, lentils and stock, and simmer 10 minutes until thick. A wet filling makes a sunken pie.',
      'Boil the peas for 3 minutes. Drain and mash the potatoes with the milk and butter and season properly.',
      'Spread the mash over the filling in a heatproof dish, rough it up with a fork, scatter the cheese and put it under a hot grill for 5 minutes until browned.',
    ],
    swap: 'Beef mince, or all lentils with an extra tin.',
    leftovers: 'Two lunch portions, and it reheats better than almost anything else in the book.',
  },

  'egg-potato-hash': {
    name: 'Potato, Pepper and Egg Hash',
    kind: 'dinner',
    tagline: 'Everything in one pan with the eggs cracked in at the end. Parboiling the potatoes first is the only thing standing between you and raw potato.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('900g potato', '900g potatoes, in 2cm dice'),
      ing('8 egg', '8 eggs'),
      ing('300g peppers', '2 peppers, diced'),
      ing('2 onion', '2 onions, sliced'),
      ing('240g reduced-sugar baked beans', 'half a large tin of baked beans'),
      ing('100g cheddar', '100g cheddar, grated'),
      ing('3 tbsp olive oil'),
      ing('4 spring onion', '4 spring onions, sliced'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Boil the diced potatoes for 7 minutes, then drain them well and let the steam die down.',
      'Fry them in the oil in a wide pan over a high heat for 8 minutes, pressing them down and turning only occasionally so they crisp rather than break up.',
      'Add the onions and peppers with the paprika and cook 6 minutes more.',
      'Stir in the beans, make eight wells, and crack an egg into each. Lid on, low heat, 5&ndash;6 minutes until the whites set.',
      'Scatter the cheese and spring onions over and serve from the pan.',
    ],
    swap: 'Leftover boiled potatoes from any night make this a fifteen-minute dinner.',
    leftovers: 'Keep two portions of the hash without eggs and fry fresh ones tomorrow; a reheated fried egg is not worth having.',
  },

  'sardine-tomato-spaghetti': {
    name: 'Sardine, Tomato and Chilli Spaghetti',
    kind: 'dinner',
    tagline: 'Tinned sardines cost very little and carry a whole dish. If you think you dislike them, this is the recipe that usually changes it.',
    time: '20 min',
    timeMins: 20,
    yield: 4,
    ingredients: [
      ing('240g tinned sardines', '2 tins sardines, drained'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('340g wholemeal pasta dry', '340g spaghetti'),
      ing('6 cloves garlic', '6 cloves garlic, sliced'),
      ing('1 onion', '1 onion, finely diced'),
      ing('30g tomato purée'),
      ing('60g parmesan', '60g hard cheese, grated'),
      ing('1 lemon'),
      ing('3 tbsp olive oil'),
      ing(negligible('chilli flakes'), 'chilli flakes, to taste'),
    ],
    method: [
      'Get the spaghetti on in well-salted water.',
      'Cook the onion in the oil for 5 minutes, then the garlic and chilli flakes for one, then the tomato pur&eacute;e for one more.',
      'Add the tomatoes and simmer hard for 8 minutes so the sauce thickens instead of watering down the pasta.',
      'Flake the sardines in at the very end and warm them through for a minute only.',
      'Drain the spaghetti, toss it through with a splash of pasta water, and finish with lemon and the cheese.',
    ],
    swap: 'Tinned mackerel or tuna. Mackerel is richer, tuna is milder.',
    leftovers: 'Two lunch portions, and good cold with an extra squeeze of lemon.',
  },

  'chicken-leek-potato-bake': {
    name: 'Chicken, Leek and Potato Bake',
    kind: 'dinner',
    tagline: 'Thighs, leeks and sliced potatoes in one dish under the grill. Nothing to watch for most of it.',
    time: '40 min',
    timeMins: 40,
    yield: 4,
    ingredients: [
      ing('640g chicken thighs', '640g chicken thigh fillets, in chunks'),
      ing('900g potato', '900g potatoes, thinly sliced'),
      ing('300g leek', '2 leeks, sliced'),
      ing('500ml chicken stock'),
      ing('150g low-fat crème fraîche'),
      ing('2 tsp mustard'),
      ing('250g frozen peas'),
      ing('80g cheddar', '80g cheddar, grated'),
      ing('2 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Parboil the sliced potatoes for 7 minutes and drain carefully so they stay in one piece.',
      'Brown the chicken in the oil in a wide ovenproof pan over a high heat, then add the leeks and cook 6 minutes.',
      'Add the stock, herbs and mustard and simmer 10 minutes until the chicken is cooked through and the liquid has reduced by about a third.',
      'Stir in the cr&egrave;me fra&icirc;che and the peas off the heat and season.',
      'Layer the potato slices over the top, scatter the cheese, and grill 6&ndash;8 minutes until browned and bubbling.',
    ],
    swap: 'Natural yogurt instead of cr&egrave;me fra&icirc;che, stirred in off the heat so it cannot split.',
    leftovers: 'Two lunch portions. Reheat covered so the potato on top does not go leathery.',
  },

  'pork-apple-mash': {
    name: 'Pork Steaks with Apple and Mustard Mash',
    kind: 'dinner',
    tagline: 'Apple cooked down in the pan juices does the job a sauce would, and takes four minutes.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('600g pork loin', '600g pork loin steaks'),
      ing('1 kg potato', '1kg potatoes, peeled and quartered'),
      ing('2 apple', '2 apples, cored and sliced'),
      ing('1 onion', '1 onion, sliced'),
      ing('300ml chicken stock'),
      ing('3 tsp mustard'),
      ing('80ml semi-skimmed milk'),
      ing('20g butter'),
      ing('300g cabbage', '300g cabbage, shredded'),
      ing('2 tbsp olive oil'),
    ],
    method: [
      'Boil the potatoes in salted water for 18 minutes.',
      'Season the pork and fry it in the oil over a medium-high heat, 4 minutes a side, until browned and cooked through with no pink. Lift it onto a plate to rest.',
      'Add the onion and apple to the pan and cook 5 minutes, then the stock, and let it bubble down by half while scraping the base.',
      'Boil the cabbage 4 minutes and drain.',
      'Drain and mash the potatoes with the milk, butter and mustard, season well, and serve the pork with the apple and pan juices spooned over.',
    ],
    swap: 'Pork chops, or chicken breast cooked the same way.',
    leftovers: 'Two lunch portions. Slice the pork before boxing it so it reheats evenly.',
  },

  'beef-bean-tacos': {
    name: 'Beef and Bean Tacos',
    kind: 'dinner',
    tagline: 'Half mince, half beans, built at the table. Twenty-five minutes and the only thing that needs attention is the pan.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('400g lean beef mince'),
      ing('480g kidney beans', '2 x 400g tins kidney beans, drained'),
      ing('400g tinned tomatoes', '1 x 400g tin chopped tomatoes'),
      ing('2 onion', '2 onions, diced'),
      ing('300g peppers', '2 peppers, diced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('6 wholemeal tortilla', '6 small tortillas'),
      ing('150g low-fat natural yogurt'),
      ing('80g cheddar', '80g cheddar, grated'),
      ing('30g tomato purée'),
      ing('1 lemon', '1 lime or lemon'),
      ing('1 tbsp olive oil'),
      ing(negligible('cumin'), '2 tsp cumin'),
    ],
    method: [
      'Brown the mince in a dry pan over a high heat, leaving it alone between stirs so it colours rather than steams.',
      'Add the oil, onions and peppers and cook 6 minutes, then the garlic and cumin for a minute and the tomato pur&eacute;e for another.',
      'Add the beans and tomatoes and simmer 10 minutes until thick enough to sit in a tortilla without running out of it.',
      'Season, and finish with the lemon juice.',
      'Warm the tortillas and build at the table with the yogurt and cheese.',
    ],
    swap: 'Drop the beef and use a third tin of beans with 200g of mushrooms browned hard first.',
    leftovers: 'Two lunch portions of the filling. Keep the tortillas and yogurt separate until the morning.',
  },

  'roast-veg-butterbean-tray': {
    name: 'Roast Vegetable and Butter Bean Tray',
    kind: 'dinner',
    tagline: 'Roast the vegetables first and add the sauce after. Vegetables cooked in the sauce from raw release water and you end up with soup.',
    time: '40 min',
    timeMins: 40,
    yield: 4,
    ingredients: [
      ing('720g cannellini beans', '3 x 400g tins butter beans, drained'),
      ing('400g courgette', '2 courgettes, in half-moons'),
      ing('450g peppers', '3 peppers, in chunks'),
      ing('2 onion', '2 red onions, in wedges'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('120g light mozzarella', '120g mozzarella, torn'),
      ing('4 slices sourdough bread', '4 thick slices of bakery bread'),
      ing('4 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Toss the courgettes, peppers and onions with 3 tbsp of the oil and plenty of salt, spread over two trays, and roast 22 minutes.',
      'Meanwhile warm the rest of the oil with the garlic and herbs for a minute, add the tomatoes and a pinch of sugar, and simmer 10 minutes.',
      'Tip the roasted vegetables and the butter beans into the sauce and fold together.',
      'Return it all to one tray, tear the mozzarella over and put it back in the oven for 8 minutes until bubbling.',
      'Serve with the bread.',
    ],
    swap: 'Aubergine or mushrooms. Any large white bean.',
    leftovers: 'Two lunch portions, and it is arguably better the next day.',
  },

  'macaroni-cheese-peas': {
    name: 'Macaroni Cheese with Peas and Bacon',
    kind: 'dinner',
    tagline: 'A proper white sauce takes four minutes and costs about thirty pence. Undercook the pasta; it finishes under the grill.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('260g wholemeal pasta dry', '260g macaroni'),
      ing('120g back bacon rashers', '120g bacon, chopped'),
      ing('30g butter'),
      ing('40g wholemeal flour'),
      ing('550ml semi-skimmed milk'),
      ing('100g cheddar', '100g cheddar, grated'),
      ing('2 tsp mustard'),
      ing('250g frozen peas'),
      ing('2 slices sourdough bread', '2 slices bread, blitzed to crumbs'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Boil the pasta three minutes short of the packet time, adding the peas for the last two. Drain.',
      'Fry the bacon in a dry pan until the fat runs and it crisps, then set it aside.',
      'Melt the butter, stir in the flour and cook it for a minute, then add the milk a splash at a time, stirring hard after each, until smooth. Simmer 3 minutes until it coats a spoon.',
      'Off the heat, stir in the mustard, two thirds of the cheese, salt and plenty of pepper.',
      'Fold through the pasta, peas and bacon, tip into a dish, top with the rest of the cheese and the breadcrumbs, and grill 5 minutes until browned.',
    ],
    swap: 'Leave the bacon out and add a tin of sweetcorn, or use smoked cheese for the same effect for less.',
    leftovers: 'Two lunch portions. Add a splash of milk before reheating; it tightens overnight.',
  },
};
