// Aldi High-Protein - dinners 13-24.

import { negligible } from '../../build/plan.mjs';

const ing = (line, display) => ({ line, display: display || line });

export const dinnersB = {
  'halloumi-veg-tray': {
    name: 'Halloumi, Egg and Roasted Vegetable Tray',
    kind: 'dinner',
    tagline: 'Halloumi and eggs on the same tray, which sounds like a lot and turns out to be the point of it.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('320g reduced-fat halloumi', '320g halloumi, in thick slices'),
      ing('6 egg', '6 eggs'),
      ing('400g courgette', '2 courgettes, in half-moons'),
      ing('450g peppers', '3 peppers, in chunks'),
      ing('2 onion', '2 red onions, in wedges'),
      ing('480g tinned chickpeas', '2 x 400g tins chickpeas, drained'),
      ing('3 tbsp olive oil'),
      ing('2 slices wholemeal bread', '2 slices bread, to serve'),
      ing('1 lemon'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Toss the courgettes, peppers, onions and chickpeas with the oil, herbs and salt, and spread over two trays rather than crowding one.',
      'Roast 20 minutes.',
      'Lay the halloumi slices on top and make six gaps; crack an egg into each gap.',
      'Roast 8&ndash;10 minutes more, until the whites have set, the yolks are still soft and the halloumi has browned.',
      'Squeeze the lemon over and serve with bread.',
    ],
    swap: 'Feta does not brown the same way but works scattered on at the end instead.',
    leftovers: 'Keep two portions of the vegetables and halloumi without the eggs, and fry fresh eggs tomorrow. A reheated baked egg is not worth having.',
  },

  'pork-mustard-mash': {
    name: 'Pork with Mustard Mash and Greens',
    kind: 'dinner',
    tagline: 'Pork tenderloin is lean enough to overcook in a moment, so it comes off the heat while it still has a blush and rests.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('700g pork tenderloin', '700g pork tenderloin, in thick medallions'),
      ing('1kg potato', '1kg potatoes, peeled and quartered'),
      ing('300g cabbage', '300g cabbage or greens, shredded'),
      ing('250g frozen peas'),
      ing('100ml semi-skimmed milk'),
      ing('20g butter'),
      ing('3 tsp mustard'),
      ing('300ml chicken stock'),
      ing('2 tbsp olive oil'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Boil the potatoes in salted water for 18 minutes.',
      'Season the pork well. Fry in the oil over a medium-high heat for 3&ndash;4 minutes a side until browned and just cooked through, then lift it onto a plate to rest.',
      'Pour the stock into the hot pan and let it bubble down by half, scraping up everything stuck to the base.',
      'Boil the cabbage and peas together for 4 minutes and drain.',
      'Drain the potatoes, steam-dry them two minutes, then mash with the milk, butter and mustard and season properly. Serve with the pan juices poured over.',
    ],
    swap: 'Pork loin steaks, or chicken breast cooked the same way.',
    leftovers: 'Two lunch portions. Slice the pork before you box it; it reheats more evenly in pieces.',
  },

  'mackerel-beetroot-potato': {
    name: 'Smoked Mackerel and Potato Salad',
    kind: 'dinner',
    tagline: 'No cooking beyond the potatoes. Smoked mackerel is already cooked, already seasoned and among the highest-protein things in the chiller.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('450g smoked mackerel fillet', '450g smoked mackerel fillets, skin off'),
      ing('1kg new potatoes', '1kg new potatoes, halved'),
      ing('200g low-fat greek yogurt'),
      ing('3 tsp mustard'),
      ing('1 lemon'),
      ing('120g mixed leaves'),
      ing('4 spring onion', '4 spring onions, sliced'),
      ing('200g green beans'),
      ing('200g cherry tomatoes', '200g cherry tomatoes, halved'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Boil the potatoes in salted water for 15 minutes, adding the green beans for the last 4. Drain and spread them on a tray to cool for ten minutes &mdash; dressing hot potatoes makes them greasy.',
      'Mix the yogurt, mustard, lemon juice, spring onions, salt and plenty of pepper.',
      'Flake the mackerel into large pieces, checking for the odd bone as you go.',
      'Fold the potatoes, green beans and tomatoes through the dressing, then the mackerel, keeping the flakes whole.',
      'Serve on the leaves.',
    ],
    swap: 'Tinned mackerel or salmon. Hot-smoked salmon if it is reduced.',
    leftovers: 'Two lunch portions, and this is one of the few dishes here that is better cold the next day than it is warm tonight.',
  },

  'tofu-edamame-noodles': {
    name: 'Tofu and Edamame Noodles',
    kind: 'dinner',
    tagline: 'Press the tofu while you chop and it browns instead of steaming. Edamame does most of the protein work.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('500g firm tofu', '500g firm tofu, pressed and cubed'),
      ing('300g edamame beans'),
      ing('260g wholewheat noodles dry', '260g noodles'),
      ing('300g cabbage', '300g cabbage, shredded'),
      ing('2 carrot', '2 carrots, in matchsticks'),
      ing('6 cloves garlic', '6 cloves garlic, sliced'),
      ing('20g ginger', '1 thumb ginger, grated'),
      ing('5 tbsp soy sauce'),
      ing('1 tbsp honey'),
      ing('2 tbsp sesame oil'),
      ing('2 tbsp olive oil'),
    ],
    method: [
      'Press the tofu between two plates with something heavy on top while you chop everything else. Ten minutes makes a real difference.',
      'Mix the soy, honey and sesame oil in a cup. Boil the noodles, drain, and toss with a drop of oil.',
      'Brown the tofu in the olive oil in a very hot pan, leaving each side alone for a minute or two, until it is gold on several faces. Lift it out.',
      'Stir-fry the cabbage and carrots for 4 minutes, then the garlic and ginger for 30 seconds, then the edamame for 2 minutes.',
      'Return the tofu and noodles, pour the sauce round the edge of the pan and toss until everything is coated.',
    ],
    swap: 'Chicken breast or prawns instead of tofu; both cook faster.',
    leftovers: 'Two lunch portions. The noodles soften but the tofu holds up well.',
  },

  'chicken-lentil-spinach-curry': {
    name: 'Chicken, Lentil and Spinach Curry',
    kind: 'dinner',
    tagline: 'Lentils thicken the sauce and push the protein up without another pan or another pound.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('700g chicken thighs', '700g chicken thigh fillets, in chunks'),
      ing('480g lentils cooked', '2 x 400g tins green lentils, drained'),
      ing('400g tinned tomatoes', '1 x 400g tin chopped tomatoes'),
      ing('200ml coconut milk light'),
      ing('2 onion', '2 onions, sliced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('20g ginger', '1 thumb ginger, grated'),
      ing('250g spinach', '250g frozen spinach'),
      ing('30g tomato purée'),
      ing('16g curry powder', '2 tbsp curry powder'),
      ing('2 tbsp olive oil'),
      ing('4 wholemeal pitta', '4 wholemeal pittas'),
    ],
    method: [
      'Brown the chicken in the oil over a high heat, then lift it out.',
      'Cook the onions 8 minutes until soft and gold, then the garlic, ginger and curry powder for a minute and the tomato purée for another.',
      'Return the chicken with the lentils, tomatoes and coconut milk, and simmer 15 minutes until the chicken is cooked through and the sauce has thickened.',
      'Stir in the frozen spinach for the last 3 minutes and season.',
      'Serve with warm pitta.',
    ],
    swap: 'Drop the chicken and add a tin of chickpeas and 300g of mushrooms browned hard.',
    leftovers: 'Two lunch portions, better the next day.',
  },

  'beef-lentil-ragu': {
    name: 'Beef and Lentil Ragù',
    kind: 'dinner',
    tagline: 'Half mince, half lentils, and the milk step that makes a quick ragù taste like a slow one.',
    time: '40 min',
    timeMins: 40,
    yield: 4,
    ingredients: [
      ing('450g lean beef mince'),
      ing('360g lentils cooked', '2 x 400g tins green lentils, drained, about a tin and a half'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('2 onion', '2 onions, finely diced'),
      ing('2 carrot', '2 carrots, finely diced'),
      ing('200g mushrooms', '200g mushrooms, finely chopped'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('150ml semi-skimmed milk'),
      ing('30g tomato purée'),
      ing('240g wholemeal pasta dry', '240g pasta'),
      ing('50g parmesan', '50g hard cheese, grated'),
      ing('2 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Brown the beef mince hard in 1 tbsp of the oil, in two batches so it colours rather than steams. Set it aside.',
      'Add the rest of the oil with the onions, carrots and mushrooms and cook 10 minutes until soft and reduced.',
      'Garlic and herbs for a minute, then the tomato purée for another.',
      'Return the mince, pour in the milk and simmer until it has nearly gone, about 5 minutes. Then add the tomatoes and lentils and simmer 15 minutes while the pasta boils.',
      'Season hard and finish with the grated cheese.',
    ],
    swap: 'All lentils for a meat-free version; keep the mushrooms, they are doing the savoury work.',
    leftovers: 'Two lunch portions. Rag&ugrave; is one of the few things that is genuinely better reheated.',
  },

  'baked-eggs-beans-feta': {
    name: 'Baked Eggs with Beans and Feta',
    kind: 'dinner',
    tagline: 'A pan of beans with eggs cracked into it. Fifteen minutes of work, and the feta goes on at the end so it keeps its edges.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('8 egg', '8 eggs'),
      ing('720g cannellini beans', '3 x 400g tins butter or cannellini beans, drained'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('2 onion', '2 onions, sliced'),
      ing('300g peppers', '2 peppers, sliced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('150g reduced-fat feta', '150g feta, crumbled'),
      ing('200g spinach', '200g frozen spinach'),
      ing('30g tomato purée'),
      ing('2 tbsp olive oil'),
      ing('4 slices wholemeal bread', '4 thick slices bread'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Cook the onions and peppers in the oil in a wide pan for 10 minutes.',
      'Garlic and paprika for a minute, then the tomato purée for another.',
      'Add the beans, tomatoes and frozen spinach with a pinch of salt and sugar, and simmer 8 minutes until thick.',
      'Make eight wells and crack an egg into each. Lid on, lowest heat, 6 minutes, until the whites have set and the yolks are still soft.',
      'Crumble the feta over and serve from the pan with the bread.',
    ],
    swap: 'Any white bean. Chickpeas stay firmer and work too.',
    leftovers: 'Keep two portions of the bean stew without eggs, and crack fresh ones into it tomorrow.',
  },

  'salmon-broccoli-pasta': {
    name: 'Salmon and Broccoli Pasta',
    kind: 'dinner',
    tagline: 'The broccoli goes into the pasta water for the last four minutes, so there is still only one pot to wash.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('500g salmon fillet', '500g salmon fillets'),
      ing('260g wholemeal pasta dry', '260g pasta'),
      ing('400g broccoli', '400g broccoli, in small florets'),
      ing('200g low-fat crème fraîche'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('150g frozen peas'),
      ing('40g parmesan', '40g hard cheese, grated'),
      ing('1 lemon'),
      ing('1 tbsp olive oil'),
      ing(negligible('black pepper'), 'plenty of black pepper'),
    ],
    method: [
      'Get the pasta on in well-salted water. Add the broccoli for the last 4 minutes and the peas for the last 2.',
      'While it cooks, season the salmon and fry it in the oil, skin down if it has skin, for 4 minutes, then turn and give it 3 more until it flakes.',
      'Lift the salmon out and flake it into large pieces, discarding the skin.',
      'Warm the garlic in the same pan for a minute, then take it off the heat and stir in the cr&egrave;me fra&icirc;che and a ladle of pasta water.',
      'Drain and add the pasta, broccoli and peas, fold in the salmon, and finish with lemon, the cheese and a lot of pepper.',
    ],
    swap: 'Tinned salmon at the end, off the heat, for a cheaper version.',
    leftovers: 'Two lunch portions. Reheat gently; a hard boil splits the sauce.',
  },

  'chicken-fajita-black-bean': {
    name: 'Chicken Fajita Bowls with Black Beans',
    kind: 'dinner',
    tagline: 'Built as a bowl rather than a wrap, so the protein carries it and the carbohydrate is the side.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('640g chicken breast', '640g chicken breast, sliced'),
      ing('480g black beans', '2 x 400g tins black beans, drained'),
      ing('450g peppers', '3 peppers, sliced'),
      ing('2 onion', '2 red onions, sliced'),
      ing('180g brown rice dry', '180g brown rice, cooked fresh'),
      ing('200g low-fat greek yogurt'),
      ing('50g cheddar', '50g cheddar, grated'),
      ing('20g fajita spice', '2 tbsp fajita seasoning'),
      ing('2 tbsp olive oil'),
      ing('1 lemon', '1 lime or lemon'),
    ],
    method: [
      'Get the rice on. Heat the oven to 220&deg;C fan.',
      'Toss the chicken, peppers and onions with the oil and fajita seasoning and spread over the largest tray in one layer.',
      'Roast 20 minutes, turning once, until the chicken is cooked through with no pink and the edges have caught.',
      'Warm the black beans with a splash of water and a pinch of salt.',
      'Squeeze the lime over the tray. Build bowls with rice, beans, the tray contents, yogurt and cheese.',
    ],
    swap: 'Chicken thighs are more forgiving and usually cheaper; give them 5 minutes longer.',
    leftovers: 'Two lunch portions of the tray and beans. Cook rice fresh tomorrow.',
  },

  'lamb-kofta-yogurt': {
    name: 'Lamb Kofta with Yogurt and Flatbread',
    kind: 'dinner',
    tagline: 'Lamb mince, onion and spice, shaped round a fork and grilled. The yogurt is not optional; it is the sauce.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('600g lean lamb mince'),
      ing('1 onion', '1 onion, very finely diced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('1 egg'),
      ing('40g rolled oats', '40g porridge oats'),
      ing('300g low-fat greek yogurt'),
      ing('4 wholemeal pitta', '4 wholemeal pittas'),
      ing('120g mixed leaves'),
      ing('200g cherry tomatoes', '200g cherry tomatoes, halved'),
      ing('1 lemon'),
      ing(negligible('cumin'), '2 tsp cumin'),
      ing(negligible('cinnamon'), '1 tsp cinnamon'),
    ],
    method: [
      'Heat the grill to high. Mix the lamb, onion, half the garlic, egg, oats, cumin, cinnamon, salt and pepper, and work it just until it holds.',
      'Shape into twelve short sausages and sit them on a foil-lined tray.',
      'Grill 12&ndash;14 minutes, turning twice, until browned all over and cooked through with no pink in the middle.',
      'Stir the remaining garlic and the lemon juice into the yogurt with a pinch of salt.',
      'Warm the pittas and serve with the leaves, tomatoes and the garlic yogurt.',
    ],
    swap: 'Beef or turkey mince. Turkey needs an extra tablespoon of oats to hold together.',
    leftovers: 'Two lunch portions. Cold kofta in a pitta with the yogurt is arguably the better meal.',
  },

  'prawn-tomato-linguine': {
    name: 'Prawn and Tomato Linguine',
    kind: 'dinner',
    tagline: 'Twenty minutes, and the prawns are in the pan for barely two of them.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('400g king prawns'),
      ing('340g wholemeal pasta dry', '340g linguine'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('6 cloves garlic', '6 cloves garlic, sliced'),
      ing('1 onion', '1 onion, finely diced'),
      ing('240g cannellini beans', '1 x 400g tin cannellini beans, drained'),
      ing('30g tomato purée'),
      ing('3 tbsp olive oil'),
      ing('1 lemon'),
      ing(negligible('chilli flakes'), 'chilli flakes, to taste'),
    ],
    method: [
      'Get the pasta on in well-salted water.',
      'Cook the onion in the oil for 5 minutes, then the garlic and chilli flakes for one and the tomato purée for one more.',
      'Add the tomatoes and beans and simmer hard for 8 minutes so the sauce thickens rather than watering down the pasta.',
      'Add the prawns and cook 2 minutes only, until they are pink and opaque through the middle.',
      'Drain the pasta, toss it through the sauce with a splash of pasta water, and finish with lemon.',
    ],
    swap: 'Frozen prawns, defrosted in the fridge. Tinned tuna, folded in off the heat, is the cheap version.',
    leftovers: 'Two lunch portions. Reheat only until hot; prawns toughen quickly on a second cooking.',
  },

  'gammon-egg-potatoes': {
    name: 'Bacon Chop, Egg and Crushed Potatoes',
    kind: 'dinner',
    tagline: 'A plate of very plain food that happens to carry about fifty grams of protein. Worth having in the rotation.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('450g lean bacon rashers', '450g bacon medallions or chops'),
      ing('6 egg', '6 eggs'),
      ing('900g new potatoes', '900g new potatoes'),
      ing('300g frozen peas'),
      ing('200g green beans'),
      ing('2 tbsp olive oil'),
      ing('20g butter'),
      ing('4 spring onion', '4 spring onions, sliced'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Boil the potatoes in salted water for 16 minutes, adding the peas and green beans for the last 4. Drain.',
      'Crush the potatoes roughly with the butter, spring onions, salt and plenty of pepper &mdash; crushed, not mashed, so there are still pieces.',
      'Fry the bacon in half the oil over a medium-high heat, 3&ndash;4 minutes a side, until browned and cooked through.',
      'Fry the eggs in the remaining oil in the same pan.',
      'Serve the bacon and eggs on the crushed potatoes with the greens.',
    ],
    swap: 'Gammon steaks, or thick-cut ham. Halloumi for a meat-free plate.',
    leftovers: 'Two portions of the bacon and potatoes; fry fresh eggs tomorrow rather than keeping them.',
  },
};
