// Aldi High-Protein - dinners 1-12.
//
// These are not the budget book's dinners with extra chicken thrown at them. The
// protein comes from a wider set - eggs, dairy, fish, pulses and cheaper cuts -
// and several dishes are built the other way round, with the protein as the base
// and the carbohydrate as the side rather than the bulk.

import { negligible } from '../../build/plan.mjs';

const ing = (line, display) => ({ line, display: display || line });

export const dinnersA = {
  'chicken-shawarma-tray': {
    name: 'Chicken Shawarma Tray with Yogurt',
    kind: 'dinner',
    tagline: 'The spice mix does the work and the yogurt at the table stops it being dry. One tray, one bowl.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('800g chicken thighs', '800g chicken thigh fillets'),
      ing('450g peppers', '3 peppers, thickly sliced'),
      ing('2 onion', '2 red onions, in wedges'),
      ing('300g low-fat greek yogurt'),
      ing('4 wholemeal pitta', '4 wholemeal pittas'),
      ing('120g mixed leaves'),
      ing('2 tbsp olive oil'),
      ing('1 lemon'),
      ing(negligible('cumin'), '2 tsp cumin'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
      ing(negligible('turmeric'), '1 tsp turmeric'),
    ],
    method: [
      'Heat the oven to 220&deg;C fan. Toss the chicken, peppers and onions with the oil, cumin, paprika, turmeric and plenty of salt.',
      'Spread over the largest tray you own in a single layer and roast 25 minutes, turning once.',
      'Check the chicken is cooked through with no pink, then squeeze the lemon over the whole tray and scrape up the juices.',
      'Warm the pittas, and serve with the leaves and a heavy spoonful of yogurt.',
    ],
    swap: 'Chicken breast if that is what is there; cut it into larger pieces so it does not dry out.',
    leftovers: 'Two lunch portions, good cold. Keep the yogurt and leaves separate until you eat them.',
  },

  'beef-black-bean-stirfry': {
    name: 'Beef and Black Bean Stir-Fry',
    kind: 'dinner',
    tagline: 'Beef strips need ninety seconds and no more. Everything is chopped before the pan goes on.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('600g lean beef strips'),
      ing('480g black beans', '2 x 400g tins black beans, drained'),
      ing('450g peppers', '3 peppers, sliced'),
      ing('200g cabbage', '200g cabbage, shredded'),
      ing('6 cloves garlic', '6 cloves garlic, sliced'),
      ing('20g ginger', '1 thumb ginger, grated'),
      ing('4 tbsp soy sauce'),
      ing('1 tbsp honey'),
      ing('2 tbsp olive oil'),
      ing('210g brown rice dry', '210g brown rice, cooked fresh'),
    ],
    method: [
      'Mix the soy and honey in a cup. Chop everything. Get the rice on; brown rice takes 25 minutes and it is the slowest thing here.',
      'Get a large pan as hot as it will go. Add half the oil and half the beef in one layer, leave it 90 seconds without touching it, then stir for another minute and lift it out. Repeat with the rest.',
      'Add the peppers and cabbage to the pan and stir-fry 4 minutes, then the garlic and ginger for 30 seconds.',
      'Return the beef with the black beans and the sauce, toss hard for a minute until everything is glossy, and season.',
    ],
    swap: 'Pork loin cut into strips, or firm tofu pressed and browned first.',
    leftovers: 'Two lunch portions of the beef and beans. Cook rice fresh tomorrow rather than keeping tonight&rsquo;s.',
  },

  'cod-bacon-butter-beans': {
    name: 'Cod with Smoky Bacon and Butter Beans',
    kind: 'dinner',
    tagline: 'The beans cook in the bacon fat and the cod sits on top and steams. One pan, and nothing needs turning.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('640g cod fillet', '640g cod fillets, defrosted'),
      ing('200g back bacon rashers', '200g bacon, chopped'),
      ing('720g cannellini beans', '3 x 400g tins butter or cannellini beans, drained'),
      ing('300g leek', '2 leeks, sliced'),
      ing('400g tinned tomatoes', '1 x 400g tin chopped tomatoes'),
      ing('400ml chicken stock'),
      ing('200g spinach', '200g frozen spinach'),
      ing('1 tbsp olive oil'),
      ing('4 slices wholemeal bread', '4 thick slices bread, to serve'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Fry the bacon in the oil in a wide pan for 5 minutes until the fat runs and the edges crisp.',
      'Add the leeks and cook 6 minutes, then the paprika for a minute.',
      'Add the beans, tomatoes and stock. Simmer 8 minutes, crushing some of the beans against the side of the pan to thicken it.',
      'Season, then sit the cod fillets on top, lid the pan, and cook 8&ndash;10 minutes on a low heat until the fish is opaque and flakes under a fork.',
      'Stir the frozen spinach into the beans around the fish for the last 3 minutes. Serve with the bread.',
    ],
    swap: 'Any white fish, or salmon, which needs two minutes less.',
    leftovers: 'Two lunch portions. Cooked fish keeps 48 hours; reheat gently so it does not go rubbery.',
  },

  'turkey-courgette-burgers': {
    name: 'Turkey and Courgette Burgers',
    kind: 'dinner',
    tagline: 'Grated courgette is what keeps a lean burger from turning into a coaster. Squeeze it out first or the mix will not hold.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('700g turkey mince lean'),
      ing('200g courgette', '1 courgette, coarsely grated'),
      ing('1 egg'),
      ing('50g rolled oats', '50g porridge oats'),
      ing('700g potato', '700g potatoes, in wedges'),
      ing('4 wholemeal roll', '4 wholemeal rolls'),
      ing('150g low-fat greek yogurt'),
      ing('100g mixed leaves'),
      ing('2 tbsp olive oil'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Toss the wedges with half the oil, the paprika and salt, and roast 30 minutes, turning once.',
      'Squeeze the grated courgette hard in a clean tea towel over the sink. You want it dry, not damp.',
      'Mix it with the turkey mince, egg, oats, salt and pepper, and shape four patties wider than the rolls. Press a dent into the middle of each.',
      'Fry in the rest of the oil over a medium-high heat, 5&ndash;6 minutes a side, until cooked through with no pink in the centre.',
      'Build in the rolls with the yogurt and leaves, wedges alongside.',
    ],
    swap: 'Chicken mince, or beef mince if you would rather have the fat back.',
    leftovers: 'Two patties and the spare wedges. Reheat the patties in the oven; a microwave makes them spongy.',
  },

  'lemon-chicken-orzo': {
    name: 'Lemon Chicken Orzo',
    kind: 'dinner',
    tagline: 'Orzo cooked in the stock like a risotto without the stirring, and it keeps for two days without rice&rsquo;s clock.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('700g chicken thighs', '700g chicken thigh fillets, in large pieces'),
      ing('260g orzo pasta dry', '260g orzo'),
      ing('2 onion', '2 onions, diced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('900ml chicken stock'),
      ing('250g frozen peas'),
      ing('200g baby spinach'),
      ing('80g parmesan', '80g hard cheese, grated'),
      ing('1 lemon'),
      ing('2 tbsp olive oil'),
    ],
    method: [
      'Brown the chicken in the oil over a high heat until coloured all over, then lift it out.',
      'Cook the onions 6 minutes, add the garlic for a minute, then the orzo, stirring until it is coated.',
      'Add the stock and return the chicken. Simmer 12 minutes, stirring now and then so the orzo does not stick, until the chicken is cooked through.',
      'Stir in the peas and spinach and give it 3 more minutes.',
      'Off the heat, add the lemon juice and the cheese, and season well.',
    ],
    swap: 'Any small pasta shape. Chicken breast works; add it back for the last 6 minutes only.',
    leftovers: 'Two lunch portions. It tightens overnight, so loosen it with a splash of water when you reheat.',
  },

  'salmon-potato-tray': {
    name: 'Salmon, New Potato and Green Bean Tray',
    kind: 'dinner',
    tagline: 'Salmon is the one place in this plan worth spending a little more. The potatoes go in first and the fish joins them late.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('600g salmon fillet', '600g salmon fillets'),
      ing('900g new potatoes', '900g new potatoes, halved'),
      ing('300g green beans'),
      ing('200g cherry tomatoes'),
      ing('150g low-fat greek yogurt'),
      ing('1 lemon'),
      ing('3 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
      ing(negligible('black pepper'), 'salt and black pepper'),
    ],
    method: [
      'Heat the oven to 210&deg;C fan. Toss the potatoes with 2 tbsp of the oil, the herbs and plenty of salt, and roast 20 minutes.',
      'Add the tomatoes and green beans, stir them through the potatoes, and make four gaps for the salmon.',
      'Sit the fillets in the gaps, brush with the last of the oil, and season.',
      'Roast 12&ndash;14 minutes more, until the salmon flakes when you push it and has gone from translucent to opaque right through.',
      'Squeeze over the lemon and serve with the yogurt stirred with a little of the lemon zest.',
    ],
    swap: 'Frozen salmon fillets, defrosted overnight in the fridge, or any white fish with two minutes less.',
    leftovers: 'Two lunch portions, very good cold with the potatoes crushed into the yogurt.',
  },

  'paneer-chickpea-curry': {
    name: 'Paneer and Chickpea Curry',
    kind: 'dinner',
    tagline: 'Paneer browns rather than melts, which is the whole reason it works here. Get it coloured before anything else goes in the pan.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('400g low-fat paneer', '400g paneer, cubed'),
      ing('480g tinned chickpeas', '2 x 400g tins chickpeas, drained'),
      ing('400g tinned tomatoes', '1 x 400g tin chopped tomatoes'),
      ing('200ml coconut milk light'),
      ing('2 onion', '2 onions, sliced'),
      ing('6 cloves garlic', '6 cloves garlic, crushed'),
      ing('20g ginger', '1 thumb ginger, grated'),
      ing('200g spinach', '200g frozen spinach'),
      ing('30g tomato purée'),
      ing('2 tbsp olive oil'),
      ing('16g curry powder', '2 tbsp curry powder'),
      ing('3 wholemeal pitta', '3 wholemeal pittas'),
    ],
    method: [
      'Brown the paneer in half the oil over a medium-high heat until it is gold on at least two sides, about 5 minutes. Lift it out.',
      'Cook the onions in the rest of the oil for 8 minutes, then the garlic, ginger and curry powder for a minute and the tomato purée for another.',
      'Add the chickpeas, tomatoes and coconut milk and simmer 10 minutes.',
      'Return the paneer with the frozen spinach and cook 4 minutes more. Season, and serve with warm pitta.',
    ],
    swap: 'Halloumi browns the same way and is saltier, so hold back on the seasoning.',
    leftovers: 'Two lunch portions. The paneer softens overnight, which some people prefer.',
  },

  'steak-pepper-rice': {
    name: 'Steak Strips with Peppers and Rice',
    kind: 'dinner',
    tagline: 'Sirloin cut into strips goes further than a steak each and cooks in three minutes. The pan has to be properly hot.',
    time: '30 min',
    timeMins: 30,
    yield: 4,
    ingredients: [
      ing('500g lean sirloin steak', '500g sirloin steak, in strips'),
      ing('450g peppers', '3 peppers, sliced'),
      ing('2 onion', '2 red onions, sliced'),
      ing('240g tinned chickpeas', '1 x 400g tin chickpeas, drained'),
      ing('250g brown rice dry', '250g brown rice, cooked fresh'),
      ing('4 cloves garlic', '4 cloves garlic, sliced'),
      ing('2 tbsp olive oil'),
      ing('150g low-fat greek yogurt'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
      ing(negligible('cumin'), '1 tsp cumin'),
    ],
    method: [
      'Get the rice on first; it takes 25 minutes and everything else takes ten.',
      'Dry the steak strips on kitchen paper and season them. Wet meat will not brown.',
      'Get a pan very hot, add half the oil and half the steak in one layer. Leave it 90 seconds, turn, give it 30 seconds more and lift it out. Repeat.',
      'Add the rest of the oil with the peppers and onions and cook 6 minutes, then the garlic, paprika and cumin for a minute and the chickpeas to warm through.',
      'Return the steak and any juices from the plate, toss once, and serve on the rice with the yogurt.',
    ],
    swap: 'Lean beef strips are usually the better value and cook identically.',
    leftovers: 'Two lunch portions of the steak and peppers. Cook rice fresh tomorrow.',
  },

  'prawn-egg-fried-rice': {
    name: 'Prawn and Egg Fried Rice',
    kind: 'dinner',
    tagline: 'The Sunday dinner, cooked at half size. Prawns go in for the last ninety seconds and not a moment longer.',
    time: '25 min',
    timeMins: 25,
    yield: 4,
    ingredients: [
      ing('300g king prawns'),
      ing('8 egg', '8 eggs, beaten'),
      ing('270g brown rice dry', '270g brown rice, cooked and cooled'),
      ing('300g frozen peas'),
      ing('200g edamame beans'),
      ing('6 spring onion', '6 spring onions, sliced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('4 tbsp soy sauce'),
      ing('2 tbsp sesame oil'),
      ing('1 tbsp olive oil'),
    ],
    method: [
      'Boil the rice, drain it and spread it on a tray to cool fast while you prepare everything else. Cold dry rice fries; warm rice turns to paste.',
      'Get the pan very hot. Add the olive oil and the beaten egg, scramble hard for 30 seconds and tip it onto a plate.',
      'Add the rice and press it flat, leaving it 30 seconds at a time between stirs so it catches. Add the peas, edamame, garlic and the white of the spring onions and toss for 2 minutes.',
      'Add the prawns and cook 90 seconds, just until they turn pink and opaque all the way through. Overcooked prawns go to rubber quickly.',
      'Return the egg, add the soy round the edge of the pan, finish with sesame oil and the green spring onion.',
    ],
    swap: 'Leave the prawns out and use ten eggs.',
    leftovers: 'None, by design. It is cooked at half size on a Sunday and eaten the same night &mdash; cooked rice is reheated once, and frying it was that once.',
  },

  'cottage-cheese-pasta-bake': {
    name: 'Spinach and Cottage Cheese Pasta Bake',
    kind: 'dinner',
    tagline: 'Cottage cheese blitzes into something close to a white sauce with none of the butter and flour. Per gram of protein it is usually among the best value in the chiller.',
    time: '40 min',
    timeMins: 40,
    yield: 4,
    ingredients: [
      ing('300g wholemeal pasta dry', '300g pasta'),
      ing('600g cottage cheese'),
      ing('300g spinach', '300g frozen spinach, defrosted and squeezed'),
      ing('4 egg', '4 eggs'),
      ing('400g tinned tomatoes', '1 x 400g tin chopped tomatoes'),
      ing('1 onion', '1 onion, diced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('120g light mozzarella', '120g mozzarella, torn'),
      ing('1 tbsp olive oil'),
      ing(negligible('mixed herbs'), '2 tsp mixed herbs'),
    ],
    method: [
      'Heat the oven to 190&deg;C fan. Boil the pasta three minutes short of the packet time and drain.',
      'Cook the onion in the oil for 6 minutes, add the garlic and herbs for a minute, then the tomatoes, and simmer 6 minutes.',
      'Beat the cottage cheese with the eggs and season well. Squeeze every drop of water out of the spinach and stir it in.',
      'Fold the pasta through the tomato sauce, tip it into a dish, spoon the cottage cheese mixture over and ripple it through.',
      'Tear the mozzarella over and bake 20 minutes until set and browned at the edges.',
    ],
    swap: 'Ricotta instead of cottage cheese gives a smoother, milder result.',
    leftovers: 'Two lunch portions, and it slices more neatly cold than hot.',
  },

  'chicken-tikka-raita': {
    name: 'Chicken Tikka with Raita',
    kind: 'dinner',
    tagline: 'Yogurt in the marinade does more than flavour it: it keeps the chicken soft through a hot oven and a second heating.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('800g chicken thighs', '800g chicken thigh fillets, in large chunks'),
      ing('200g low-fat greek yogurt', '200g yogurt, for the marinade'),
      ing('60g tikka paste'),
      ing('450g peppers', '3 peppers, in chunks'),
      ing('2 onion', '2 red onions, in wedges'),
      ing('240g raita'),
      ing('4 wholemeal pitta', '4 wholemeal pittas'),
      ing('120g mixed leaves'),
      ing('1 tbsp olive oil'),
      ing('1 lemon'),
    ],
    method: [
      'Heat the oven to 220&deg;C fan. Mix the yogurt and tikka paste in a large bowl, add the chicken and turn it until every piece is coated. Ten minutes is enough if that is all you have.',
      'Spread the chicken, peppers and onions over a large tray, trickle over the oil and season.',
      'Roast 25 minutes, turning once, until the edges have charred slightly and the chicken is cooked through with no pink.',
      'Squeeze over the lemon. Serve with warm pitta, the leaves and the raita.',
    ],
    swap: 'Any curry paste. Paneer or firm tofu marinates the same way and needs 15 minutes rather than 25.',
    leftovers: 'Two lunch portions. Keep the raita and leaves separate.',
  },

  'turkey-chilli-yogurt': {
    name: 'Turkey Chilli with Beans and Yogurt',
    kind: 'dinner',
    tagline: 'Leaner than a beef chilli and, with three tins of beans in it, higher in both protein and fibre.',
    time: '35 min',
    timeMins: 35,
    yield: 4,
    ingredients: [
      ing('550g turkey mince lean'),
      ing('480g kidney beans', '2 x 400g tins kidney beans, drained'),
      ing('240g black beans', '1 x 400g tin black beans, drained'),
      ing('800g tinned tomatoes', '2 x 400g tins chopped tomatoes'),
      ing('2 onion', '2 onions, diced'),
      ing('300g peppers', '2 peppers, diced'),
      ing('4 cloves garlic', '4 cloves garlic, crushed'),
      ing('30g tomato purée'),
      ing('200g low-fat greek yogurt'),
      ing('180g brown rice dry', '180g brown rice, cooked fresh'),
      ing('2 tbsp olive oil'),
      ing(negligible('cumin'), '2 tsp cumin'),
      ing(negligible('smoked paprika'), '2 tsp smoked paprika'),
    ],
    method: [
      'Brown the turkey mince hard in 1 tbsp of the oil, breaking it up. Lean mince sticks readily, so keep it moving once it colours.',
      'Add the rest of the oil with the onions and peppers and cook 8 minutes.',
      'Garlic and spices for a minute, then the tomato purée for another.',
      'Add all three tins of beans and the tomatoes with a splash of water, and simmer 15 minutes while the rice cooks.',
      'Season hard, and serve with a spoon of yogurt on each plate.',
    ],
    swap: 'Beef mince, or drop the meat and add a fourth tin of beans with 200g of browned mushrooms.',
    leftovers: 'Two lunch portions, better on the second day. Cook rice fresh tomorrow.',
  },
};
